# Generated by Django 5.2.6 on 2026-02-28 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0002_v3_new_tables_and_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlhealth',
            name='control',
            field=models.OneToOneField(db_column='control_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='health', serialize=False, to='compliance.compliancecontrol'),
        ),
    ]
