# Generated by Django 5.2.6 on 2026-02-28 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0004_create_audit_evidence_v3_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='complianceaudit',
            name='audit_code_id',
            field=models.CharField(blank=True, help_text='Unique human-readable/external identifier', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='compliancecontrol',
            name='control_code_id',
            field=models.CharField(blank=True, help_text='Unique human-readable/external identifier', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='complianceevidence',
            name='evidence_code_id',
            field=models.CharField(blank=True, help_text='Unique human-readable/external identifier', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='complianceframework',
            name='framework_code_id',
            field=models.CharField(blank=True, help_text='Unique human-readable/external identifier', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='compliancepolicy',
            name='policy_code_id',
            field=models.CharField(blank=True, help_text='Unique human-readable/external identifier', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='controlassertion',
            name='assertion_code_id',
            field=models.CharField(blank=True, help_text='Unique human-readable/external identifier', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='controlrequirementmapping',
            name='control_requirement_map_code_id',
            field=models.CharField(blank=True, help_text='Unique human-readable/external identifier', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='evidencetemplate',
            name='evidence_template_code_id',
            field=models.CharField(blank=True, help_text='Unique human-readable/external identifier', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='frameworkversion',
            name='framework_version_code_id',
            field=models.CharField(blank=True, help_text='Unique human-readable/external identifier', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='requirement_code_id',
            field=models.CharField(blank=True, help_text='Unique human-readable/external identifier', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='requirementpointoffocus',
            name='pof_code_id',
            field=models.CharField(blank=True, help_text='Unique human-readable/external identifier', max_length=100, unique=True),
        ),
    ]
