# Generated by Django 5.2.6 on 2026-02-28 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0005_add_code_id_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancecontrol',
            name='automation_opportunity',
            field=models.TextField(blank=True, help_text='Where automation could apply'),
        ),
        migrations.AddField(
            model_name='compliancecontrol',
            name='automation_recommendation',
            field=models.TextField(blank=True, help_text='Recommended automation approach'),
        ),
        migrations.AddField(
            model_name='controldepartmentmap',
            name='department_code',
            field=models.CharField(blank=True, help_text='Human-readable department code (e.g. from catalog)', max_length=100),
        ),
        migrations.AddField(
            model_name='controlevidencerequirement',
            name='retention_guidance',
            field=models.TextField(blank=True, help_text='Guidance for how long to retain this evidence'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='statement_paraphrase',
            field=models.TextField(blank=True, help_text='Paraphrased or summarized requirement text'),
        ),
    ]
