# Generated by Django 5.2.6 on 2026-03-01 08:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0007_phase8_constraints'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationFramework',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('framework', models.ForeignKey(db_column='framework_id', on_delete=django.db.models.deletion.CASCADE, related_name='org_enabled', to='compliance.complianceframework')),
            ],
            options={
                'db_table': 'organization_frameworks',
                'ordering': ['framework__name'],
                'indexes': [models.Index(fields=['organization_id', 'enabled'], name='organizatio_organiz_f6f8c2_idx')],
                'unique_together': {('organization_id', 'framework')},
            },
        ),
    ]
