# Generated by Django 5.2.6 on 2026-03-04 21:06

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0010_controlassertion_assertion_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlassertion',
            name='data_source_id',
            field=models.UUIDField(blank=True, help_text='Connector instance', null=True),
        ),
        migrations.AddField(
            model_name='controlassertion',
            name='organization_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='controlassertion',
            name='rendered_text',
            field=models.TextField(blank=True, help_text='Cached human sentence'),
        ),
        migrations.AddField(
            model_name='controlassertion',
            name='scope_json',
            field=models.JSONField(blank=True, default=dict, help_text='Filtering: privileged users, prod accounts, etc.'),
        ),
        migrations.AddField(
            model_name='metricsnapshot',
            name='organization_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metricsnapshot',
            name='source_run_id',
            field=models.UUIDField(blank=True, help_text='Trace connector run', null=True),
        ),
        migrations.AlterField(
            model_name='compliancepolicy',
            name='requirement_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='controlassertion',
            name='assertion_code_id',
            field=models.CharField(blank=True, help_text='Org-stable identifier', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='metricsnapshot',
            name='raw_payload_ref',
            field=models.TextField(blank=True, help_text='raw_evidence_ref'),
        ),
        migrations.CreateModel(
            name='AssertionTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assertion_template_code_id', models.CharField(help_text='Template code (e.g. MFA_COVERAGE)', max_length=100, unique=True)),
                ('name', models.CharField(max_length=300)),
                ('description_human', models.TextField(blank=True, help_text='Sentence users see')),
                ('assertion_type', models.CharField(blank=True, default='config', help_text='config/identity/vuln/logging/attestation', max_length=30)),
                ('resource_type', models.CharField(blank=True, help_text='user/device/bucket/repo/vendor/etc.', max_length=50)),
                ('metric_key', models.CharField(help_text='Canonical metric name', max_length=100)),
                ('default_threshold_operator', models.CharField(default='>=', max_length=10)),
                ('default_threshold_value', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('default_eval_frequency', models.CharField(default='daily', max_length=20)),
                ('requires_connectors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('control', models.ForeignKey(blank=True, db_column='control_id', help_text='Baseline control library', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assertion_templates', to='compliance.compliancecontrol')),
            ],
            options={
                'db_table': 'assertion_templates',
                'ordering': ['assertion_template_code_id'],
            },
        ),
        migrations.AddField(
            model_name='controlassertion',
            name='assertion_template',
            field=models.ForeignKey(blank=True, db_column='assertion_template_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_assertions', to='compliance.assertiontemplate'),
        ),
    ]
