# Data migration: seed 30 assertion templates covering ~80% SOC2 automation
# Connectors: AWS, Okta/Azure AD, GitHub, Vulnerability scanner

from decimal import Decimal
from django.db import migrations


TEMPLATES = [
    # --- Identity (Okta / Azure AD) — 8 templates ---
    {
        "assertion_template_code_id": "MFA_PRIVILEGED_COVERAGE",
        "name": "Privileged MFA Coverage",
        "description_human": "Percentage of privileged users with MFA enabled is at least 99%.",
        "assertion_type": "identity",
        "resource_type": "user",
        "metric_key": "mfa_privileged_coverage_pct",
        "default_threshold_operator": ">=",
        "default_threshold_value": Decimal("99"),
        "default_eval_frequency": "daily",
        "requires_connectors": ["okta", "azure_ad"],
    },
    {
        "assertion_template_code_id": "FAILED_LOGIN_ALERT",
        "name": "Failed Login Alert",
        "description_human": "Excessive failed logins trigger an alert within SLA.",
        "assertion_type": "identity",
        "resource_type": "user",
        "metric_key": "failed_login_alert_within_sla",
        "default_threshold_operator": ">=",
        "default_threshold_value": Decimal("1"),
        "default_eval_frequency": "hourly",
        "requires_connectors": ["okta", "azure_ad"],
    },
    {
        "assertion_template_code_id": "INACTIVE_ADMIN_ACCOUNTS",
        "name": "No Inactive Admin Accounts",
        "description_human": "No inactive admin accounts older than 30 days.",
        "assertion_type": "identity",
        "resource_type": "user",
        "metric_key": "inactive_admin_accounts_count",
        "default_threshold_operator": "<=",
        "default_threshold_value": Decimal("0"),
        "default_eval_frequency": "daily",
        "requires_connectors": ["okta", "azure_ad"],
    },
    {
        "assertion_template_code_id": "IDENTITY_LOGS_RETENTION",
        "name": "Identity Access Logs Retention",
        "description_human": "Identity access logs are retained for at least 90 days.",
        "assertion_type": "logging",
        "resource_type": "log",
        "metric_key": "identity_logs_retention_days",
        "default_threshold_operator": ">=",
        "default_threshold_value": Decimal("90"),
        "default_eval_frequency": "weekly",
        "requires_connectors": ["okta", "azure_ad"],
    },
    {
        "assertion_template_code_id": "UNUSED_IAM_KEYS",
        "name": "No Unused IAM Keys",
        "description_human": "No unused IAM access keys older than 90 days.",
        "assertion_type": "identity",
        "resource_type": "user",
        "metric_key": "unused_iam_keys_count",
        "default_threshold_operator": "<=",
        "default_threshold_value": Decimal("0"),
        "default_eval_frequency": "daily",
        "requires_connectors": ["aws"],
    },
    {
        "assertion_template_code_id": "PASSWORD_POLICY_COMPLIANCE",
        "name": "Password Policy Compliance",
        "description_human": "IAM password policy meets minimum requirements (length, complexity, expiry).",
        "assertion_type": "config",
        "resource_type": "policy",
        "metric_key": "password_policy_compliant",
        "default_threshold_operator": ">=",
        "default_threshold_value": Decimal("1"),
        "default_eval_frequency": "daily",
        "requires_connectors": ["okta", "azure_ad", "aws"],
    },
    {
        "assertion_template_code_id": "DORMANT_ACCOUNTS_REMOVED",
        "name": "Dormant Accounts Removed",
        "description_human": "No dormant accounts (no login > 90 days) remain active.",
        "assertion_type": "identity",
        "resource_type": "user",
        "metric_key": "dormant_accounts_count",
        "default_threshold_operator": "<=",
        "default_threshold_value": Decimal("0"),
        "default_eval_frequency": "weekly",
        "requires_connectors": ["okta", "azure_ad"],
    },
    {
        "assertion_template_code_id": "ROOT_ACCOUNT_MFA",
        "name": "Root Account MFA",
        "description_human": "AWS root account has MFA enabled.",
        "assertion_type": "identity",
        "resource_type": "user",
        "metric_key": "root_mfa_enabled",
        "default_threshold_operator": ">=",
        "default_threshold_value": Decimal("1"),
        "default_eval_frequency": "daily",
        "requires_connectors": ["aws"],
    },
    # --- AWS / Cloud — 10 templates ---
    {
        "assertion_template_code_id": "S3_ENCRYPTION_ENABLED",
        "name": "S3 Bucket Encryption",
        "description_human": "All S3 buckets have server-side encryption enabled.",
        "assertion_type": "config",
        "resource_type": "bucket",
        "metric_key": "s3_encrypted_buckets_pct",
        "default_threshold_operator": ">=",
        "default_threshold_value": Decimal("100"),
        "default_eval_frequency": "daily",
        "requires_connectors": ["aws"],
    },
    {
        "assertion_template_code_id": "S3_PUBLIC_ACCESS_BLOCKED",
        "name": "S3 Public Access Blocked",
        "description_human": "All S3 buckets have public access blocked.",
        "assertion_type": "config",
        "resource_type": "bucket",
        "metric_key": "s3_public_access_blocked_pct",
        "default_threshold_operator": ">=",
        "default_threshold_value": Decimal("100"),
        "default_eval_frequency": "daily",
        "requires_connectors": ["aws"],
    },
    {
        "assertion_template_code_id": "SECURITY_GROUP_NO_WORLD",
        "name": "No Open Ports to World",
        "description_human": "No security groups have open ports to 0.0.0.0/0 except approved.",
        "assertion_type": "config",
        "resource_type": "security_group",
        "metric_key": "security_groups_with_world_access_count",
        "default_threshold_operator": "<=",
        "default_threshold_value": Decimal("0"),
        "default_eval_frequency": "daily",
        "requires_connectors": ["aws"],
    },
    {
        "assertion_template_code_id": "CLOUDTRAIL_ENABLED_ALL_REGIONS",
        "name": "CloudTrail Enabled All Regions",
        "description_human": "CloudTrail is enabled in all regions.",
        "assertion_type": "logging",
        "resource_type": "trail",
        "metric_key": "cloudtrail_regions_coverage_pct",
        "default_threshold_operator": ">=",
        "default_threshold_value": Decimal("100"),
        "default_eval_frequency": "daily",
        "requires_connectors": ["aws"],
    },
    {
        "assertion_template_code_id": "EBS_ENCRYPTION",
        "name": "EBS Volume Encryption",
        "description_human": "All EBS volumes are encrypted at rest.",
        "assertion_type": "config",
        "resource_type": "volume",
        "metric_key": "ebs_encrypted_volumes_pct",
        "default_threshold_operator": ">=",
        "default_threshold_value": Decimal("100"),
        "default_eval_frequency": "daily",
        "requires_connectors": ["aws"],
    },
    {
        "assertion_template_code_id": "RDS_ENCRYPTION",
        "name": "RDS Encryption at Rest",
        "description_human": "All RDS instances have encryption at rest enabled.",
        "assertion_type": "config",
        "resource_type": "database",
        "metric_key": "rds_encrypted_instances_pct",
        "default_threshold_operator": ">=",
        "default_threshold_value": Decimal("100"),
        "default_eval_frequency": "daily",
        "requires_connectors": ["aws"],
    },
    {
        "assertion_template_code_id": "CLOUDTRAIL_ENCRYPTION",
        "name": "CloudTrail Log Encryption",
        "description_human": "CloudTrail logs are encrypted.",
        "assertion_type": "config",
        "resource_type": "trail",
        "metric_key": "cloudtrail_encryption_enabled",
        "default_threshold_operator": ">=",
        "default_threshold_value": Decimal("1"),
        "default_eval_frequency": "daily",
        "requires_connectors": ["aws"],
    },
    {
        "assertion_template_code_id": "EC2_PUBLIC_IP_RESTRICTED",
        "name": "EC2 Public IP Restricted",
        "description_human": "EC2 instances with public IPs are restricted to approved use cases.",
        "assertion_type": "config",
        "resource_type": "instance",
        "metric_key": "ec2_unauthorized_public_ip_count",
        "default_threshold_operator": "<=",
        "default_threshold_value": Decimal("0"),
        "default_eval_frequency": "daily",
        "requires_connectors": ["aws"],
    },
    {
        "assertion_template_code_id": "IAM_KEY_ROTATION",
        "name": "IAM Key Rotation",
        "description_human": "No IAM access keys older than 90 days without rotation.",
        "assertion_type": "identity",
        "resource_type": "user",
        "metric_key": "iam_keys_over_90_days_count",
        "default_threshold_operator": "<=",
        "default_threshold_value": Decimal("0"),
        "default_eval_frequency": "daily",
        "requires_connectors": ["aws"],
    },
    # --- GitHub / Change Management — 6 templates ---
    {
        "assertion_template_code_id": "BRANCH_PROTECTION_ENABLED",
        "name": "Branch Protection Enabled",
        "description_human": "Branch protection is enabled on the default branch for all repos.",
        "assertion_type": "config",
        "resource_type": "repo",
        "metric_key": "branch_protection_enabled_pct",
        "default_threshold_operator": ">=",
        "default_threshold_value": Decimal("100"),
        "default_eval_frequency": "daily",
        "requires_connectors": ["github"],
    },
    {
        "assertion_template_code_id": "PR_APPROVAL_REQUIRED",
        "name": "Pull Request Approval Required",
        "description_human": "Pull request approval is required before merge on protected branches.",
        "assertion_type": "config",
        "resource_type": "repo",
        "metric_key": "pr_approval_required_pct",
        "default_threshold_operator": ">=",
        "default_threshold_value": Decimal("100"),
        "default_eval_frequency": "daily",
        "requires_connectors": ["github"],
    },
    {
        "assertion_template_code_id": "NO_DIRECT_PUSH_MAIN",
        "name": "No Direct Push to Main",
        "description_human": "No direct pushes to main/master branch; all changes via PR.",
        "assertion_type": "config",
        "resource_type": "repo",
        "metric_key": "repos_allowing_direct_push_count",
        "default_threshold_operator": "<=",
        "default_threshold_value": Decimal("0"),
        "default_eval_frequency": "daily",
        "requires_connectors": ["github"],
    },
    {
        "assertion_template_code_id": "CODE_REVIEW_REQUIRED",
        "name": "Code Review Required",
        "description_human": "Code review is required for all merges to protected branches.",
        "assertion_type": "config",
        "resource_type": "repo",
        "metric_key": "code_review_required_pct",
        "default_threshold_operator": ">=",
        "default_threshold_value": Decimal("100"),
        "default_eval_frequency": "daily",
        "requires_connectors": ["github"],
    },
    {
        "assertion_template_code_id": "REQUIRE_STATUS_CHECKS",
        "name": "Status Checks Required",
        "description_human": "Status checks are required before merge on protected branches.",
        "assertion_type": "config",
        "resource_type": "repo",
        "metric_key": "status_checks_required_pct",
        "default_threshold_operator": ">=",
        "default_threshold_value": Decimal("100"),
        "default_eval_frequency": "daily",
        "requires_connectors": ["github"],
    },
    {
        "assertion_template_code_id": "REPO_PERMISSION_RESTRICTED",
        "name": "Repository Permission Restricted",
        "description_human": "Repository admin/write permissions are restricted to approved users.",
        "assertion_type": "config",
        "resource_type": "repo",
        "metric_key": "repos_with_overly_broad_permissions_count",
        "default_threshold_operator": "<=",
        "default_threshold_value": Decimal("0"),
        "default_eval_frequency": "weekly",
        "requires_connectors": ["github"],
    },
    # --- Vulnerability Scanner — 6 templates ---
    {
        "assertion_template_code_id": "CRITICAL_VULN_SLA",
        "name": "Critical Vulnerability SLA",
        "description_human": "No critical vulnerabilities (CVSS ≥ 9) older than 7 days.",
        "assertion_type": "vuln",
        "resource_type": "vulnerability",
        "metric_key": "critical_vulns_over_7_days_count",
        "default_threshold_operator": "<=",
        "default_threshold_value": Decimal("0"),
        "default_eval_frequency": "daily",
        "requires_connectors": ["tenable", "qualys", "rapid7"],
    },
    {
        "assertion_template_code_id": "HIGH_VULN_SLA",
        "name": "High Vulnerability SLA",
        "description_human": "No high vulnerabilities (CVSS 7–8.9) older than 30 days.",
        "assertion_type": "vuln",
        "resource_type": "vulnerability",
        "metric_key": "high_vulns_over_30_days_count",
        "default_threshold_operator": "<=",
        "default_threshold_value": Decimal("0"),
        "default_eval_frequency": "daily",
        "requires_connectors": ["tenable", "qualys", "rapid7"],
    },
    {
        "assertion_template_code_id": "PATCH_SLA_MET",
        "name": "Patch SLA Met",
        "description_human": "Patch remediation SLA is met for critical and high vulnerabilities.",
        "assertion_type": "vuln",
        "resource_type": "vulnerability",
        "metric_key": "patch_sla_met_pct",
        "default_threshold_operator": ">=",
        "default_threshold_value": Decimal("100"),
        "default_eval_frequency": "daily",
        "requires_connectors": ["tenable", "qualys", "rapid7"],
    },
    {
        "assertion_template_code_id": "VULN_SCAN_FREQUENCY",
        "name": "Vulnerability Scan Frequency",
        "description_human": "Vulnerability scans run at least weekly.",
        "assertion_type": "vuln",
        "resource_type": "scan",
        "metric_key": "vuln_scan_days_since_last",
        "default_threshold_operator": "<=",
        "default_threshold_value": Decimal("7"),
        "default_eval_frequency": "daily",
        "requires_connectors": ["tenable", "qualys", "rapid7"],
    },
    {
        "assertion_template_code_id": "ASSET_COVERAGE",
        "name": "Asset Coverage in Scan",
        "description_human": "All critical assets are included in vulnerability scans.",
        "assertion_type": "vuln",
        "resource_type": "asset",
        "metric_key": "assets_in_scan_coverage_pct",
        "default_threshold_operator": ">=",
        "default_threshold_value": Decimal("100"),
        "default_eval_frequency": "weekly",
        "requires_connectors": ["tenable", "qualys", "rapid7"],
    },
    {
        "assertion_template_code_id": "CRITICAL_VULN_COUNT",
        "name": "Zero Critical Vulnerabilities",
        "description_human": "No open critical vulnerabilities in production assets.",
        "assertion_type": "vuln",
        "resource_type": "vulnerability",
        "metric_key": "critical_vulns_open_count",
        "default_threshold_operator": "<=",
        "default_threshold_value": Decimal("0"),
        "default_eval_frequency": "daily",
        "requires_connectors": ["tenable", "qualys", "rapid7"],
    },
]


def seed_assertion_templates(apps, schema_editor):
    AssertionTemplate = apps.get_model("compliance", "AssertionTemplate")
    for t in TEMPLATES:
        AssertionTemplate.objects.update_or_create(
            assertion_template_code_id=t["assertion_template_code_id"],
            defaults={
                "name": t["name"],
                "description_human": t["description_human"],
                "control": None,
                "assertion_type": t["assertion_type"],
                "resource_type": t["resource_type"],
                "metric_key": t["metric_key"],
                "default_threshold_operator": t["default_threshold_operator"],
                "default_threshold_value": t["default_threshold_value"],
                "default_eval_frequency": t["default_eval_frequency"],
                "requires_connectors": t["requires_connectors"],
            },
        )


def reverse_seed(apps, schema_editor):
    AssertionTemplate = apps.get_model("compliance", "AssertionTemplate")
    codes = [t["assertion_template_code_id"] for t in TEMPLATES]
    AssertionTemplate.objects.filter(assertion_template_code_id__in=codes).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0011_assertion_data_model_reconciliation"),
    ]

    operations = [
        migrations.RunPython(seed_assertion_templates, reverse_seed),
    ]
