# Generated by Django 5.2.6 on 2026-03-04 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0012_seed_assertion_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='assertiontemplate',
            name='evidence_artifact_type',
            field=models.CharField(blank=True, help_text='Automated snapshot / Evidence upload', max_length=50),
        ),
        migrations.AddField(
            model_name='assertiontemplate',
            name='framework_code_id',
            field=models.CharField(blank=True, help_text='Framework (e.g. SOC2)', max_length=50),
        ),
        migrations.AddField(
            model_name='assertiontemplate',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assertiontemplate',
            name='rendered_sentence_template',
            field=models.TextField(blank=True, help_text='Template with {{threshold_value}}, {{days}}, etc.'),
        ),
        migrations.AddField(
            model_name='assertiontemplate',
            name='scope_default_json',
            field=models.JSONField(blank=True, default=dict, help_text='Default scope filters'),
        ),
        migrations.AddField(
            model_name='assertiontemplate',
            name='severity_default',
            field=models.CharField(blank=True, help_text='critical/high/medium/low', max_length=20),
        ),
        migrations.AlterField(
            model_name='assertiontemplate',
            name='assertion_type',
            field=models.CharField(blank=True, default='config', help_text='config/identity/vuln/logging/attestation/sdlc/process/recovery/endpoint/monitoring', max_length=30),
        ),
    ]
