# Generated by Django 5.2.6 on 2026-03-05 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0014_seed_assertion_templates_from_csv'),
    ]

    operations = [
        migrations.AddField(
            model_name='assertiontemplate',
            name='config_connector_display',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='assertiontemplate',
            name='config_frequency_display',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='assertiontemplate',
            name='config_scope_display',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='assertiontemplate',
            name='config_threshold_display',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='assertiontemplate',
            name='evidence_90_day_report_status_default',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='assertiontemplate',
            name='evidence_90_day_report_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='assertiontemplate',
            name='evidence_auto_generated_status_default',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='assertiontemplate',
            name='evidence_auto_generated_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='assertiontemplate',
            name='history_30d_pass_rate_default',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='assertiontemplate',
            name='history_90d_pass_rate_default',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='assertiontemplate',
            name='overview_last_run_default',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='assertiontemplate',
            name='overview_last_value_default',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='assertiontemplate',
            name='overview_policy_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='assertiontemplate',
            name='overview_rendered_sentence_example',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assertiontemplate',
            name='overview_status_default',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
