# Generated by Django 5.2.6 on 2026-03-10 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0020_audit_lifecycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policytemplate',
            name='policy_template_code_id',
            field=models.CharField(help_text='e.g. POLSEC001', max_length=100, unique=True),
        ),
    ]
