# Generated by Django 5.2.6 on 2026-03-14 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0021_alter_policytemplate_policy_template_code_id'),
        ('compliance', '0023_audit_org_fk'),
    ]

    operations = [
    ]
