# Generated by Django 5.2.6 on 2026-02-27 02:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0001_identity_schema_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('email', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=64)),
                ('status', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='UserTeamMap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('team_id', models.UUIDField(db_index=True)),
            ],
            options={
                'db_table': 'user_team_map',
            },
        ),
    ]
