# Generated by Django 5.2.6 on 2026-03-15 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0002_affiliate_application_notes_affiliate_rejected_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliate',
            name='partner_type',
            field=models.CharField(choices=[('affiliate', 'Affiliate'), ('consultant', 'Consultant'), ('audit_partner', 'Audit Partner'), ('technology_partner', 'Technology Partner')], db_index=True, default='affiliate', max_length=30),
        ),
    ]
