# Generated by Django 5.2.6 on 2026-02-27 02:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platform_org', '0002_sync_sources_governance_set_and_ldap'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField()),
                ('name', models.CharField(max_length=255)),
                ('parent_department_id', models.UUIDField(blank=True, null=True)),
                ('head_personnel_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'departments',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField()),
                ('role_name', models.CharField(max_length=255)),
                ('role_type', models.CharField(blank=True, choices=[('control_owner', 'Control owner'), ('evidence_provider', 'Evidence provider'), ('internal_auditor', 'Internal auditor'), ('compliance_manager', 'Compliance manager'), ('approver', 'Approver'), ('executive', 'Executive')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='SyncSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField()),
                ('source_type', models.CharField(choices=[('okta', 'Okta'), ('azure_ad', 'Azure AD'), ('workday', 'Workday'), ('csv', 'CSV'), ('manual', 'Manual'), ('ldap', 'LDAP')], max_length=32)),
                ('governance_set', models.SmallIntegerField(default=1)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('failed', 'Failed'), ('paused', 'Paused')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sync_sources',
            },
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField()),
                ('external_hr_id', models.CharField(blank=True, max_length=255)),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('employment_status', models.CharField(choices=[('active', 'Active'), ('terminated', 'Terminated'), ('contractor', 'Contractor'), ('leave', 'Leave')], max_length=32)),
                ('job_title', models.CharField(blank=True, max_length=255)),
                ('department_id', models.UUIDField(blank=True, null=True)),
                ('manager_personnel_id', models.UUIDField(blank=True, null=True)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'personnel',
                'indexes': [models.Index(fields=['organization_id'], name='personnel_organiz_90340a_idx'), models.Index(fields=['manager_personnel_id'], name='personnel_manager_36c23c_idx')],
            },
        ),
        migrations.CreateModel(
            name='PersonnelRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('personnel_id', models.UUIDField()),
                ('role_id', models.UUIDField()),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'personnel_roles',
                'indexes': [models.Index(fields=['role_id'], name='personnel_r_role_id_8e0995_idx')],
                'unique_together': {('personnel_id', 'role_id', 'effective_from')},
            },
        ),
    ]
