# Generated by Django 5.2.6 on 2026-02-28 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_org', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='department_code',
            field=models.CharField(blank=True, help_text='Human-readable department code', max_length=100),
        ),
    ]
