# Generated by Django 5.2.6 on 2026-03-10 22:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_org', '0020_personnel_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('region_group', models.CharField(choices=[('NA', 'North America'), ('EU', 'EU'), ('ASIA', 'Asia'), ('MEA', 'MEA'), ('LATAM', 'Latin America'), ('AU', 'Australia')], default='NA', max_length=32)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'db_table': 'countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(blank=True, default='', max_length=5)),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
                'db_table': 'currencies',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('org_id', models.IntegerField(editable=False, help_text='Customer-facing org identifier, starts at 100', unique=True)),
                ('name', models.CharField(max_length=255)),
                ('tier', models.CharField(default='free', max_length=50)),
                ('legal_name', models.CharField(blank=True, default='', max_length=255)),
                ('display_name', models.CharField(blank=True, default='', max_length=255)),
                ('primary_domain', models.CharField(blank=True, default='', max_length=255)),
                ('secondary_domains', models.TextField(blank=True, default='')),
                ('physical_address', models.TextField(blank=True, default='')),
                ('industry', models.CharField(blank=True, default='', max_length=120)),
                ('jurisdiction_country', models.CharField(blank=True, default='', max_length=10)),
                ('jurisdiction_state', models.CharField(blank=True, default='', max_length=10)),
                ('timezone', models.CharField(blank=True, default='UTC+00:00', max_length=64)),
                ('currency', models.CharField(blank=True, default='USD', max_length=3)),
                ('fiscal_year_start_month', models.SmallIntegerField(default=1)),
                ('primary_contact_name', models.CharField(blank=True, default='', max_length=255)),
                ('primary_contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('billing_contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('security_contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('data_residency_region', models.CharField(blank=True, default='', max_length=64)),
                ('default_environment_id', models.UUIDField(blank=True, null=True)),
                ('enforce_mfa', models.BooleanField(default=False)),
                ('sso_enabled', models.BooleanField(default=False)),
                ('status', models.CharField(default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.UUIDField(blank=True, help_text='User UUID who created this org', null=True)),
                ('changed_by', models.UUIDField(blank=True, help_text='User UUID who last changed this org', null=True)),
                ('changed_at', models.DateTimeField(blank=True, help_text='Timestamp of last change', null=True)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'db_table': 'organizations',
            },
        ),
        migrations.CreateModel(
            name='Timezone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('label', models.CharField(blank=True, default='', max_length=120)),
                ('utc_offset', models.SmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Timezone',
                'verbose_name_plural': 'Timezones',
                'db_table': 'timezones',
                'ordering': ['utc_offset', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=50)),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='environments', to='platform_org.organization')),
            ],
            options={
                'verbose_name': 'Environment',
                'verbose_name_plural': 'Environments',
                'db_table': 'environments',
            },
        ),
        migrations.CreateModel(
            name='OrgConnector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('connector_type', models.CharField(choices=[('cloud', 'Cloud (AWS/Azure/GCP)'), ('kubernetes', 'Kubernetes'), ('email', 'Email provider'), ('slack', 'Slack / Teams'), ('hris', 'HRIS (Workday, BambooHR)'), ('siem', 'SIEM'), ('vuln_scanner', 'Vulnerability scanner'), ('dev_platform', 'Dev platform (GitHub etc.)'), ('itsm', 'ITSM (Jira, ServiceNow)'), ('evidence_storage', 'Evidence storage (S3 etc.)')], max_length=64)),
                ('governance_set', models.SmallIntegerField(choices=[(2, 'Global (all modules)'), (3, 'Module-scoped')], default=3)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('credentials_ref', models.CharField(blank=True, max_length=255)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Org connector',
                'verbose_name_plural': 'Org connectors',
                'db_table': 'org_connectors',
                'indexes': [models.Index(fields=['organization_id', 'connector_type'], name='org_connect_organiz_98edd7_idx')],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('team_type', models.CharField(choices=[('department', 'Department'), ('engineering', 'Engineering'), ('security', 'Security'), ('compliance', 'Compliance'), ('finance', 'Finance'), ('ops', 'Ops'), ('custom', 'Custom')], default='custom', max_length=32)),
                ('active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(blank=True, db_column='department_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='platform_org.department')),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='platform_org.organization')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'db_table': 'teams',
            },
        ),
        migrations.CreateModel(
            name='OrganizationRegion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(blank=True, default='', max_length=255)),
                ('currency_code', models.CharField(blank=True, default='', max_length=3)),
                ('primary_contact_name', models.CharField(blank=True, max_length=255)),
                ('primary_contact_email', models.EmailField(blank=True, max_length=255)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(db_column='country_id', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform_org.country')),
            ],
            options={
                'verbose_name': 'Organization region',
                'verbose_name_plural': 'Organization regions',
                'db_table': 'organization_regions',
                'indexes': [models.Index(fields=['organization_id'], name='organizatio_organiz_a52f2f_idx')],
                'unique_together': {('organization_id', 'country_id')},
            },
        ),
        migrations.CreateModel(
            name='OrgConnectorModuleScope',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module', models.CharField(choices=[('discovery', 'Discovery'), ('security', 'Security'), ('compliance', 'Compliance'), ('cost', 'Cost'), ('health', 'Health'), ('change', 'Change'), ('evidence', 'Evidence')], max_length=64)),
                ('org_connector', models.ForeignKey(db_column='org_connector_id', on_delete=django.db.models.deletion.CASCADE, related_name='module_scopes', to='platform_org.orgconnector')),
            ],
            options={
                'verbose_name': 'Org connector module scope',
                'verbose_name_plural': 'Org connector module scopes',
                'db_table': 'org_connector_module_scope',
                'indexes': [models.Index(fields=['org_connector_id', 'module'], name='org_connect_org_con_5236ab_idx')],
                'unique_together': {('org_connector', 'module')},
            },
        ),
        migrations.CreateModel(
            name='OrgCurrency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('currency', models.ForeignKey(db_column='currency_id', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform_org.currency')),
            ],
            options={
                'verbose_name': 'Org currency',
                'verbose_name_plural': 'Org currencies',
                'db_table': 'org_currencies',
                'indexes': [models.Index(fields=['organization_id'], name='org_curr_org_id_idx')],
                'unique_together': {('organization_id', 'currency')},
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='platform_org.country')),
            ],
            options={
                'verbose_name': 'State / Province',
                'verbose_name_plural': 'States / Provinces',
                'db_table': 'states',
                'ordering': ['name'],
                'unique_together': {('country', 'code')},
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(db_index=True)),
                ('team', models.ForeignKey(db_column='team_id', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='platform_org.team')),
            ],
            options={
                'verbose_name': 'Team member',
                'verbose_name_plural': 'Team members',
                'db_table': 'team_members',
                'unique_together': {('team', 'user_id')},
            },
        ),
    ]
