# Generated by Django 5.2.6 on 2026-03-10 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platform_org', '0021_country_currency_organization_timezone_environment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='department',
        ),
    ]
