# Generated by Django 5.2.6 on 2026-02-27 02:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platform_reports', '0001_reports_schema_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('as_of', models.DateTimeField()),
                ('framework_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('total_controls', models.IntegerField(blank=True, null=True)),
                ('compliant_count', models.IntegerField(blank=True, null=True)),
                ('gap_count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'compliance_summary',
            },
        ),
        migrations.CreateModel(
            name='MaterializedAssetSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_id', models.UUIDField(db_index=True, unique=True)),
                ('refreshed_at', models.DateTimeField()),
                ('attribute_count', models.IntegerField(blank=True, null=True)),
                ('relationship_count', models.IntegerField(blank=True, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('risk_score', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('compliance_status', models.CharField(blank=True, max_length=32)),
            ],
            options={
                'db_table': 'materialized_asset_summary',
            },
        ),
        migrations.CreateModel(
            name='RiskTrends',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('snapshot_date', models.DateField(db_index=True)),
                ('asset_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('composite_score', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('trend_direction', models.CharField(blank=True, max_length=16)),
            ],
            options={
                'db_table': 'risk_trends',
            },
        ),
    ]
