# Generated by Django 5.2.6 on 2026-02-27 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_add_enable_analytics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='site_name',
            field=models.CharField(default='Opticini', help_text='Site name displayed in header and emails', max_length=100),
        ),
    ]
