# Generated by Django 5.2.6 on 2026-02-27 02:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('risk', '0001_risk_schema_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetRiskScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_id', models.UUIDField(db_index=True)),
                ('operational_risk', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('security_risk', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('compliance_risk', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('financial_risk', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('composite_score', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
            ],
            options={
                'db_table': 'asset_risk_scores',
            },
        ),
        migrations.CreateModel(
            name='RiskFactor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_id', models.UUIDField(db_index=True)),
                ('factor_type', models.CharField(max_length=64)),
                ('source_module', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'risk_factors',
            },
        ),
        migrations.CreateModel(
            name='RiskRegister',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=512)),
                ('severity', models.CharField(max_length=32)),
                ('status', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'risk_register',
            },
        ),
    ]
