# Generated by Django 5.2.6 on 2026-02-27 02:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platform_monitoring', '0001_monitoring_schema_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_id', models.UUIDField(db_index=True)),
                ('severity', models.CharField(max_length=32)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('incident_id', models.UUIDField(blank=True, db_index=True, null=True)),
            ],
            options={
                'db_table': 'alerts',
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_id', models.UUIDField(db_index=True)),
                ('severity', models.CharField(max_length=32)),
                ('opened_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'incidents',
            },
        ),
        migrations.CreateModel(
            name='UptimeMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_id', models.UUIDField(db_index=True)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('uptime_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('check_count', models.IntegerField(blank=True, null=True)),
                ('down_count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'uptime_metrics',
            },
        ),
    ]
