import type { FeatureDetailConfig } from "@/components/feature-detail-page"

type CostI18nPayload = Omit<FeatureDetailConfig, "colors">
type CostPagePatch = { features: { cost: CostI18nPayload } }

function cost(
  title: string,
  subtitle: string,
  tagline: string,
  posStrong: string,
  posBody: string,
  sectionLabel: string,
  sectionTitle: string,
  outcomeLabel: string,
  outcomeText: string,
  ctaTitle: string,
  ctaSubtitle: string,
  extraLabel: string,
  extraTitle: string,
  cards: {
    c1: string; c2: string; c3: string; c4: string; c5: string;
    i1: string[]; i2: string[]; i3: string[]; i4: string[]; i5: string[];
    extra: { title: string; sub: string }[];
  }
): CostI18nPayload {
  return {
    title,
    subtitle,
    tagline,
    planeNum: 9,
    stats: [
      { value: "Real-time", label: "cost tracking" },
      { value: "Cloud +", label: "on-prem unified" },
      { value: "Per team", label: "cost attribution" },
      { value: "Waste", label: "detection built in" },
    ],
    posStrong,
    posBody,
    sectionLabel,
    sectionTitle,
    cards: [
      { icon: "🗺️", title: cards.c1, items: cards.i1 },
      { icon: "🎯", title: cards.c2, items: cards.i2 },
      { icon: "🗑️", title: cards.c3, items: cards.i3 },
      { icon: "⚡", title: cards.c4, items: cards.i4 },
      { icon: "📊", title: cards.c5, items: cards.i5 },
    ],
    compareLabel: "",
    compareTitle: "",
    compareOld: "",
    compareNew: "",
    compareRows: [],
    outcomeLabel,
    outcomeText,
    ctaTitle,
    ctaSubtitle,
    extraSection: {
      label: extraLabel,
      title: extraTitle,
      cards: cards.extra,
    },
  }
}

const COST_EN = cost(
  "Cost",
  "Visibility before optimization",
  "FinOps-grade visibility built directly into infrastructure monitoring.",
  "Opticini Cost provides real-time and historical visibility into infrastructure spending across local, hybrid, and cloud.",
  "It connects usage, configuration, and performance with financial impact so finance, IT, and engineering operate from one source of truth.",
  "Core Capabilities",
  "From spend to waste to optimization in one place",
  "Outcome",
  "Infrastructure spend becomes intentional, visible, and defensible with measurable savings tied to real actions.",
  "Turn usage into financial clarity",
  "See where every dollar goes and connect spend to performance, change, and risk.",
  "Who It's For",
  "One cost view shared across every stakeholder",
  {
    c1: "Unified Cost Discovery",
    c2: "Usage-Based Attribution",
    c3: "Waste and Optimization Detection",
    c4: "Change-to-Cost Correlation",
    c5: "Forecasting and Budget Guardrails",
    i1: [
      "On-prem infrastructure cost modeling",
      "Cloud cost ingestion (AWS, Azure, GCP)",
      "Hybrid environment normalization",
      "Environment segmentation (prod/dev)",
    ],
    i2: [
      "CPU, memory, disk, and network cost mapping",
      "Application-level cost attribution",
      "Team, project, and business-unit allocation",
      "Service and workload tagging",
    ],
    i3: [
      "Idle and underutilized resources",
      "Overprovisioned compute and storage",
      "Zombie services and orphaned assets",
      "Redundant environments and unused snapshots",
    ],
    i4: [
      "Cost impact of deployments and config changes",
      "Spike detection tied to scaling events",
      "Drift-driven cost increases",
      "Rollback cost validation",
    ],
    i5: [
      "Trend-based cost forecasting",
      "Budget thresholds and alerts",
      "Unexpected spend anomaly detection",
      "What-if analysis for scaling decisions",
    ],
    extra: [
      { title: "Finance and FinOps", sub: "Budget control, forecasting, and accountability." },
      { title: "Platform and Infrastructure", sub: "Right-sizing and waste reduction." },
      { title: "Engineering Leadership", sub: "Cost-aware architecture decisions." },
      { title: "Executives", sub: "ROI visibility and infrastructure efficiency." },
    ],
  }
)

const COST_PT = cost("Custo","Visibilidade antes da otimizacao","Visibilidade no nivel FinOps integrada nativamente ao monitoramento de infraestrutura.","O plano de Custo do Opticini oferece visao em tempo real e historica dos gastos em ambientes locais, hibridos e nuvem.","Ele conecta uso, configuracao e desempenho ao impacto financeiro para que Financas, TI e Engenharia decidam com a mesma fonte de verdade.","Capacidades principais","De gasto para desperdicio e otimizacao em um so lugar","Resultado","Gastos de infraestrutura passam a ser intencionais, visiveis e defensaveis, com economia mensuravel ligada a acoes reais.","Converta uso em clareza financeira","Veja para onde vai cada valor e conecte gastos com desempenho, mudanca e risco.","Para quem e","Uma visao de custo compartilhada por todos os stakeholders",{c1:"Descoberta Unificada de Custos",c2:"Atribuicao Baseada em Uso",c3:"Deteccao de Desperdicio e Otimizacao",c4:"Correlacao Mudanca-Custo",c5:"Previsao e Guardrails de Orcamento",i1:["Modelagem de custo para infraestrutura on-prem","Ingestao de custos em nuvem (AWS, Azure, GCP)","Normalizacao de ambientes hibridos","Segmentacao por ambiente (prod/dev)"],i2:["Mapeamento de custo de CPU, memoria, disco e rede","Atribuicao de custo por aplicacao","Rateio por time, projeto e unidade de negocio","Tagueamento de servico e workload"],i3:["Recursos ociosos e subutilizados","Compute e storage superprovisionados","Servicos zumbis e ativos orfaos","Ambientes redundantes e snapshots sem uso"],i4:["Impacto de custo de deploys e mudancas de configuracao","Deteccao de picos ligada a eventos de escala","Aumento de custo causado por drift","Validacao de custo de rollback"],i5:["Previsao de custos baseada em tendencia","Limites de orcamento e alertas","Deteccao de anomalias de gasto inesperado","Analise de cenarios para decisoes de escala"],extra:[{title:"Financas e FinOps",sub:"Controle de orcamento, previsao e responsabilizacao."},{title:"Plataforma e Infraestrutura",sub:"Right-sizing e reducao de desperdicio."},{title:"Lideranca de Engenharia",sub:"Decisoes arquiteturais orientadas a custo."},{title:"Executivos",sub:"Visibilidade de ROI e eficiencia de infraestrutura."}]})
const COST_ES = cost("Costo","Visibilidad antes de optimizar","Visibilidad nivel FinOps integrada al monitoreo de infraestructura.","Opticini Costo ofrece vista en tiempo real e historica del gasto en local, hibrido y nube.","Conecta uso, configuracion y rendimiento con impacto financiero para que Finanzas, TI e Ingenieria decidan con una sola verdad.","Capacidades clave","Del gasto al desperdicio y la optimizacion en un solo lugar","Resultado","El gasto de infraestructura se vuelve intencional, visible y defendible con ahorros medibles ligados a acciones reales.","Convierte uso en claridad financiera","Ve a donde va cada monto y conecta gasto con rendimiento, cambio y riesgo.","Para quien es","Una vista de costo compartida por todos los actores",{c1:"Descubrimiento unificado de costos",c2:"Atribucion basada en uso",c3:"Deteccion de desperdicio y optimizacion",c4:"Correlacion cambio-costo",c5:"Pronostico y guardrails de presupuesto",i1:["Modelado de costos on-prem","Ingestion de costos cloud (AWS, Azure, GCP)","Normalizacion de entornos hibridos","Segmentacion por entorno (prod/dev)"],i2:["Mapeo de costos de CPU, memoria, disco y red","Atribucion de costo por aplicacion","Asignacion por equipo, proyecto y unidad","Etiquetado por servicio y workload"],i3:["Recursos ociosos y subutilizados","Compute y storage sobreaprovisionados","Servicios zombi y activos huerfanos","Entornos redundantes y snapshots sin uso"],i4:["Impacto de costo por despliegues y cambios","Deteccion de picos ligados a escalado","Incrementos por drift","Validacion de costo de rollback"],i5:["Pronostico por tendencia","Umbrales de presupuesto y alertas","Deteccion de anomalias de gasto","Analisis what-if para decisiones de escalado"],extra:[{title:"Finanzas y FinOps",sub:"Control presupuestario, pronostico y responsabilidad."},{title:"Plataforma e Infraestructura",sub:"Right-sizing y reduccion de desperdicio."},{title:"Liderazgo de Ingenieria",sub:"Decisiones de arquitectura conscientes de costo."},{title:"Ejecutivos",sub:"Visibilidad de ROI y eficiencia de infraestructura."}]})
const COST_FR = cost("Cout","Visibilite avant optimisation","Visibilite niveau FinOps integree au monitoring d'infrastructure.","Opticini Cout fournit une vue en temps reel et historique des depenses infra en local, hybride et cloud.","Il relie usage, configuration et performance a l'impact financier pour aligner Finance, IT et Engineering.","Capacites principales","Des depenses au gaspillage puis a l'optimisation en un seul endroit","Resultat","Les depenses infrastructure deviennent intentionnelles, visibles et defendables avec des economies mesurables.","Transformer l'usage en clarte financiere","Voir ou va chaque euro et relier depenses, performance, changement et risque.","Pour qui","Une vue cout partagee par toutes les parties prenantes",{c1:"Decouverte unifiee des couts",c2:"Attribution basee sur l'usage",c3:"Detection du gaspillage et optimisation",c4:"Correlation changement-cout",c5:"Prevision et garde-fous budgetaires",i1:["Modelisation des couts on-prem","Ingestion des couts cloud (AWS, Azure, GCP)","Normalisation des environnements hybrides","Segmentation par environnement (prod/dev)"],i2:["Cartographie des couts CPU, memoire, disque, reseau","Attribution des couts au niveau applicatif","Allocation par equipe, projet, business unit","Tagging par service et workload"],i3:["Ressources inactives/sous-utilisees","Compute et stockage surprovisionnes","Services zombies et actifs orphelins","Environnements redondants et snapshots inutilises"],i4:["Impact cout des deploiements et changements config","Detection des pics lies au scaling","Augmentations de cout dues au drift","Validation du cout de rollback"],i5:["Prevision de cout basee sur tendance","Seuils budgetaires et alertes","Detection d'anomalies de depense","Analyse what-if pour decisions de scaling"],extra:[{title:"Finance et FinOps",sub:"Controle budgetaire, prevision et responsabilisation."},{title:"Plateforme et Infrastructure",sub:"Right-sizing et reduction du gaspillage."},{title:"Leadership Engineering",sub:"Decisions d'architecture sensibles au cout."},{title:"Executifs",sub:"Visibilite ROI et efficacite infrastructure."}]})
const COST_DE = cost("Kosten","Transparenz vor Optimierung","FinOps-Niveau Transparenz direkt im Infrastrukturmonitoring.","Opticini Kosten bietet Echtzeit- und Verlaufssicht auf Infrastrukturkosten in On-Prem, Hybrid und Cloud.","Es verknupft Nutzung, Konfiguration und Performance mit Finanzwirkung fur gemeinsame Entscheidungen von Finance, IT und Engineering.","Kernfunktionen","Von Ausgaben zu Verschwendung zu Optimierung an einem Ort","Ergebnis","Infrastrukturkosten werden planbar, sichtbar und belastbar mit messbaren Einsparungen aus realen MaBnahmen.","Nutzung in Finanzklarheit verwandeln","Sehen Sie wohin jeder Betrag geht und verknupfen Sie Kosten mit Performance, Anderung und Risiko.","Fur wen","Eine gemeinsame Kostenansicht fur alle Stakeholder",{c1:"Einheitliche Kostenerkennung",c2:"Nutzungsbasierte Zuordnung",c3:"Verschwendungs- und Optimierungserkennung",c4:"Anderungs-Kosten-Korrelation",c5:"Prognose und Budget-Guardrails",i1:["Kostenmodellierung fur On-Prem-Infrastruktur","Cloud-Kosten-Ingestion (AWS, Azure, GCP)","Normalisierung hybrider Umgebungen","Umgebungssegmentierung (prod/dev)"],i2:["Kostenmapping fur CPU, Speicher, Disk, Netzwerk","Kostenzuordnung auf Anwendungsebene","Allokation nach Team, Projekt, Bereich","Tagging nach Service und Workload"],i3:["Inaktive und unterausgelastete Ressourcen","Uberprovisioniertes Compute und Storage","Zombie-Services und verwaiste Assets","Redundante Umgebungen und ungenutzte Snapshots"],i4:["Kostenimpact von Deployments und Config-Anderungen","Spike-Erkennung bei Skalierungsereignissen","Drift-bedingte Kostensteigerungen","Rollback-Kostenvalidierung"],i5:["Trendbasierte Kostenprognose","Budgetschwellen und Alerts","Anomalieerkennung unerwarteter Ausgaben","What-if-Analyse fur Skalierungsentscheidungen"],extra:[{title:"Finance und FinOps",sub:"Budgetkontrolle, Prognose und Verantwortlichkeit."},{title:"Plattform und Infrastruktur",sub:"Right-sizing und Verschwendungsreduktion."},{title:"Engineering Leadership",sub:"Kostenbewusste Architekturentscheidungen."},{title:"Executives",sub:"ROI-Transparenz und Infrastruktureffizienz."}]})
const COST_IT = cost("Costo","Visibilita prima dell'ottimizzazione","Visibilita livello FinOps integrata nel monitoraggio infrastrutturale.","Opticini Costo offre visione in tempo reale e storica della spesa infrastrutturale su on-prem, ibrido e cloud.","Collega uso, configurazione e performance all'impatto economico per allineare Finance, IT ed Engineering.","Capacita principali","Da spesa a spreco a ottimizzazione in un unico punto","Risultato","La spesa infrastrutturale diventa intenzionale, visibile e difendibile con risparmi misurabili.","Trasforma l'uso in chiarezza finanziaria","Vedi dove va ogni euro e collega spesa a performance, cambiamento e rischio.","Per chi","Una vista costo condivisa da tutti gli stakeholder",{c1:"Scoperta costi unificata",c2:"Attribuzione basata sull'uso",c3:"Rilevamento sprechi e ottimizzazione",c4:"Correlazione cambiamento-costo",c5:"Previsione e guardrail di budget",i1:["Modellazione costi on-prem","Ingestion costi cloud (AWS, Azure, GCP)","Normalizzazione ambienti ibridi","Segmentazione per ambiente (prod/dev)"],i2:["Mappatura costi CPU, memoria, disco e rete","Attribuzione costi a livello applicativo","Allocazione per team, progetto, business unit","Tagging per servizio e workload"],i3:["Risorse inattive/sottoutilizzate","Compute e storage sovradimensionati","Servizi zombie e asset orfani","Ambienti ridondanti e snapshot inutilizzati"],i4:["Impatto costo di deploy e cambi config","Rilevamento picchi legati a scaling","Aumenti costo guidati da drift","Validazione costo rollback"],i5:["Previsione costi basata su trend","Soglie budget e alert","Rilevamento anomalie di spesa","Analisi what-if per decisioni di scaling"],extra:[{title:"Finance e FinOps",sub:"Controllo budget, previsione e accountability."},{title:"Piattaforma e Infrastruttura",sub:"Right-sizing e riduzione sprechi."},{title:"Leadership Engineering",sub:"Decisioni architetturali cost-aware."},{title:"Executives",sub:"Visibilita ROI ed efficienza infrastrutturale."}]})
const COST_RU = cost("Стоимость","Видимость до оптимизации","Видимость уровня FinOps, встроенная в мониторинг инфраструктуры.","Opticini Стоимость дает реальное и историческое понимание инфраструктурных затрат в on-prem, hybrid и cloud.","Связывает использование, конфигурацию и performance с финансовым эффектом для общих решений Finance, IT и Engineering.","Ключевые возможности","От затрат к перерасходу и оптимизации в одном месте","Результат","Расходы на инфраструктуру становятся осознанными, прозрачными и обоснованными с измеримой экономией.","Преобразуйте использование в финансовую ясность","Видите куда уходит каждый рубль и связывайте затраты с performance, изменениями и риском.","Для кого","Единый взгляд на стоимость для всех стейкхолдеров",{c1:"Единое обнаружение затрат",c2:"Атрибуция по использованию",c3:"Выявление перерасхода и оптимизация",c4:"Корреляция изменение-стоимость",c5:"Прогноз и бюджетные guardrails",i1:["Моделирование стоимости on-prem инфраструктуры","Ingestion cloud-затрат (AWS, Azure, GCP)","Нормализация hybrid-сред","Сегментация по средам (prod/dev)"],i2:["Маппинг затрат CPU, память, диск, сеть","Атрибуция затрат на уровне приложений","Распределение по командам, проектам, бизнес-юнитам","Тегирование по сервисам и workload"],i3:["Неиспользуемые и недогруженные ресурсы","Сверхпровижининг compute и storage","Zombie-сервисы и orphan-активы","Избыточные среды и неиспользуемые snapshot"],i4:["Стоимость deploy и config-изменений","Выявление всплесков при scaling","Рост затрат из-за drift","Валидация стоимости rollback"],i5:["Прогноз затрат по трендам","Бюджетные пороги и alert","Выявление аномалий непредвиденных затрат","What-if анализ для решений по scaling"],extra:[{title:"Finance и FinOps",sub:"Контроль бюджета, прогноз и accountability."},{title:"Платформа и Инфраструктура",sub:"Right-sizing и снижение перерасхода."},{title:"Руководство Engineering",sub:"Cost-aware архитектурные решения."},{title:"Executives",sub:"Прозрачность ROI и эффективность инфраструктуры."}]})
const COST_SV = cost("Kostnad","Synlighet fore optimering","FinOps-niva synlighet inbyggd i infrastrukturmonitorering.","Opticini Kostnad ger realtids- och historisk insyn i infrastrukturkostnader over on-prem, hybrid och moln.","Den kopplar anvandning, konfiguration och prestanda till ekonomisk effekt for gemensamma beslut i Finance, IT och Engineering.","Karnfunktioner","Fran kostnad till sloseri till optimering pa ett stalle","Resultat","Infrastrukturutgifter blir avsiktliga, synliga och forsvarbara med matbara besparingar.","Gor anvandning till ekonomisk klarhet","Se vart varje krona gar och koppla kostnad till prestanda, andring och risk.","For vem","En gemensam kostnadsbild for alla intressenter",{c1:"Enhetlig kostnadsupptackt",c2:"Anvandningsbaserad attributering",c3:"Detektion av sloseri och optimering",c4:"Andring-till-kostnad-korrelation",c5:"Prognos och budget-guardrails",i1:["Kostnadsmodellering for on-prem infrastruktur","Inlasning av molnkostnader (AWS, Azure, GCP)","Normalisering av hybrida miljoer","Segmentering per miljo (prod/dev)"],i2:["Kostnadsmappning av CPU, minne, disk och natverk","Kostnadsattributering pa applikationsniva","Allokering per team, projekt och affarsenhet","Taggning per tjanst och arbetslast"],i3:["Inaktiva och underutnyttjade resurser","Overprovisionerad compute och lagring","Zombie-tjanster och foraldrade tillgangar","Redundanta miljoer och oanvanda snapshots"],i4:["Kostnadspaverkan av deployer och konfigandringar","Spikdetektion kopplad till skalning","Driftdrivna kostnadsokningar","Rollback-kostnadsvalidering"],i5:["Trendbaserad kostnadsprognos","Budgetgranser och larm","Anomalidetektion for ovantad spend","What-if-analys for skalningsbeslut"],extra:[{title:"Finance och FinOps",sub:"Budgetkontroll, prognos och ansvar."},{title:"Plattform och Infrastruktur",sub:"Right-sizing och minskat sloseri."},{title:"Engineering-ledning",sub:"Kostnadsmedvetna arkitekturbeslut."},{title:"Ledning",sub:"ROI-synlighet och infrastruktureffektivitet."}]})
const COST_NO = cost("Kostnad","Synlighet for optimalisering","FinOps-niva synlighet innebygd i infrastrukturmonitorering.","Opticini Kostnad gir sanntids- og historisk innsikt i infrastrukturkostnader pa on-prem, hybrid og sky.","Kobler bruk, konfigurasjon og ytelse til finansielt utfall for felles beslutninger i Finance, IT og Engineering.","Kjernekapabiliteter","Fra kostnad til slosing til optimalisering pa ett sted","Resultat","Infrastrukturkostnader blir bevisste, synlige og forsvarbare med malbare besparelser.","Gjor bruk til finansiell klarhet","Se hvor hver krone gar og koble kostnad til ytelse, endring og risiko.","For hvem","Ett kostnadsbilde delt pa tvers av alle interessenter",{c1:"Samlet kostnadsoppdagelse",c2:"Bruksbasert attribusjon",c3:"Deteksjon av slosing og optimalisering",c4:"Endring-til-kostnad-korrelasjon",c5:"Prognose og budsjett-guardrails",i1:["Kostnadsmodellering for on-prem infrastruktur","Inntak av skykostnader (AWS, Azure, GCP)","Normalisering av hybride miljoer","Miljosegmentering (prod/dev)"],i2:["Kostnadskartlegging av CPU, minne, disk og nettverk","Kostnadsattribusjon pa applikasjonsniva","Allokering per team, prosjekt og forretningsenhet","Tagging per tjeneste og workload"],i3:["Inaktive og underutnyttede ressurser","Overprovisjonert compute og lagring","Zombie-tjenester og foreldreloste eiendeler","Redundante miljoer og ubrukte snapshots"],i4:["Kostnadseffekt av deployer og konfigendringer","Spikdeteksjon knyttet til skalering","Drift-drevne kostnadsokninger","Validering av rollback-kostnad"],i5:["Trendbasert kostnadsprognose","Budsjettgrenser og varsler","Anomalideteksjon av uventet spend","What-if-analyse for skaleringsvalg"],extra:[{title:"Finance og FinOps",sub:"Budsjettkontroll, prognose og ansvarlighet."},{title:"Plattform og Infrastruktur",sub:"Right-sizing og reduksjon av slosing."},{title:"Engineering-ledelse",sub:"Kostnadsbevisste arkitekturbeslutninger."},{title:"Ledelse",sub:"ROI-innsikt og infrastruktureffektivitet."}]})
const COST_DA = cost("Omkostning","Synlighed for optimering","FinOps-niveau synlighed indbygget i infrastrukturovervagning.","Opticini Omkostning giver realtids- og historisk indsigt i infrastrukturudgifter pa on-prem, hybrid og cloud.","Det forbinder brug, konfiguration og performance med finansiel effekt for faelles beslutninger pa tvrs af Finance, IT og Engineering.","Kernefunktioner","Fra udgift til spild til optimering samlet et sted","Resultat","Infrastrukturudgifter bliver intentionelle, synlige og forsvarlige med malbare besparelser.","Gor brug til finansiel klarhed","Se hvor hver krone gar og koble udgifter til performance, andring og risiko.","For hvem","En samlet omkostningsvisning for alle interessenter",{c1:"Samlet omkostningsopdagelse",c2:"Brugsbaseret attributering",c3:"Detektion af spild og optimering",c4:"Andring-til-omkostning korrelation",c5:"Prognose og budget-guardrails",i1:["Omkostningsmodellering for on-prem infrastruktur","Indlaesning af cloud-omkostninger (AWS, Azure, GCP)","Normalisering af hybride miljoer","Segmentering pr. miljo (prod/dev)"],i2:["Omkostningsmapping af CPU, hukommelse, disk og netvaerk","Applikationsbaseret omkostningsattributering","Allokering pr. team, projekt og forretningsenhed","Tagging pr. service og workload"],i3:["Inaktive og underudnyttede ressourcer","Overprovisioneret compute og storage","Zombie-services og foraldreloste aktiver","Redundante miljoer og ubrugte snapshots"],i4:["Omkostningsimpact af deploys og konfigandringer","Spikdetektion koblet til skalering","Drift-drevne omkostningsstigninger","Validering af rollback-omkostning"],i5:["Trendbaseret omkostningsprognose","Budgettaerskler og alarmer","Anomalidetektion for uventet spend","What-if analyse for skaleringsvalg"],extra:[{title:"Finance og FinOps",sub:"Budgetkontrol, prognose og ansvar."},{title:"Platform og Infrastruktur",sub:"Right-sizing og reduktion af spild."},{title:"Engineering-ledelse",sub:"Omkostningsbevidste arkitekturbeslutninger."},{title:"Ledelse",sub:"ROI-synlighed og infrastruktureffektivitet."}]})
const COST_ZH = cost("成本","优化之前先可视","FinOps 级可视化，原生集成在基础设施监控中。","Opticini 成本提供本地、混合与云环境的实时与历史成本可视化。","将使用量、配置和性能与财务影响关联，让财务、IT 和工程基于同一事实做决策。","核心能力","从支出到浪费再到优化，一站完成","结果","基础设施支出变得有意图、可见、可辩护，并能量化节省。","将使用量转化为财务清晰度","看清每一笔花费，并将支出与性能、变更、风险关联。","适用对象","所有利益相关方共享同一成本视图",{c1:"统一成本发现",c2:"基于使用量的归因",c3:"浪费检测与优化",c4:"变更到成本的关联",c5:"预测与预算护栏",i1:["本地基础设施成本建模","云成本采集（AWS、Azure、GCP）","混合环境标准化","按环境分段（prod/dev）"],i2:["CPU、内存、磁盘、网络成本映射","应用级成本归因","按团队/项目/业务单元分摊","按服务与工作负载打标"],i3:["空闲与低利用资源","过度配置的计算与存储","僵尸服务与孤儿资产","冗余环境与未使用快照"],i4:["部署与配置变更的成本影响","与扩缩容事件关联的峰值检测","由 drift 驱动的成本上涨","回滚成本校验"],i5:["基于趋势的成本预测","预算阈值与告警","异常支出检测","用于扩缩容决策的 what-if 分析"],extra:[{title:"财务与 FinOps",sub:"预算控制、预测与责任落实。"}, {title:"平台与基础设施",sub:"Right-sizing 与浪费降低。"}, {title:"工程管理层",sub:"成本感知的架构决策。"}, {title:"管理层",sub:"ROI 可视化与基础设施效率。"}]})
const COST_JA = cost("コスト","最適化の前に可視化","FinOps レベルの可視化を、インフラ監視にネイティブ統合。","Opticini コストはオンプレ/ハイブリッド/クラウドのインフラ支出をリアルタイムと履歴で可視化します。","利用量・構成・性能を財務影響と結びつけ、Finance・IT・Engineering が同じ事実で意思決定できます。","コア機能","支出・無駄・最適化を一箇所で","結果","インフラ支出は意図的・可視的・説明可能になり、実行に紐づく節約を測定できます。","利用を財務の明確さへ変える","すべての支出先を把握し、コストを性能・変更・リスクと結びつけます。","対象者","すべてのステークホルダーが共有するコスト視点",{c1:"統合コスト検出",c2:"利用量ベースの配賦",c3:"無駄検知と最適化",c4:"変更とコストの相関",c5:"予測と予算ガードレール",i1:["オンプレ基盤のコストモデル化","クラウドコスト取り込み（AWS, Azure, GCP）","ハイブリッド環境の正規化","環境別セグメント（prod/dev）"],i2:["CPU・メモリ・ディスク・ネットワークのコストマッピング","アプリケーション単位のコスト配賦","チーム/プロジェクト/事業部配分","サービス/ワークロードのタグ付け"],i3:["アイドル/低利用リソース","過剰プロビジョニングされた compute/storage","ゾンビサービスと孤立資産","冗長環境と未使用 snapshot"],i4:["デプロイ/設定変更のコスト影響","スケールイベント連動のスパイク検知","drift によるコスト増加","rollback コスト検証"],i5:["トレンドベースのコスト予測","予算しきい値とアラート","予期せぬ支出の異常検知","スケーリング判断の what-if 分析"],extra:[{title:"Finance と FinOps",sub:"予算管理、予測、責任管理。"}, {title:"プラットフォーム/インフラ",sub:"Right-sizing と無駄削減。"}, {title:"Engineering リーダー",sub:"コスト意識のアーキ判断。"}, {title:"経営層",sub:"ROI 可視化とインフラ効率。"}]})
const COST_KO = cost("비용","최적화 전에 가시화","FinOps 수준 가시성을 인프라 모니터링에 기본 통합.","Opticini 비용은 온프레미스/하이브리드/클라우드 인프라 지출을 실시간·이력으로 가시화합니다.","사용량, 구성, 성능을 재무 영향과 연결해 Finance, IT, Engineering이 같은 사실로 의사결정합니다.","핵심 기능","지출부터 낭비, 최적화까지 한곳에서","결과","인프라 지출이 의도적이고 가시적이며 설명 가능해지고, 실행에 연결된 절감이 측정됩니다.","사용량을 재무 명확성으로 전환","모든 비용 흐름을 보고, 비용을 성능/변경/위험과 연결하세요.","대상","모든 이해관계자가 공유하는 단일 비용 뷰",{c1:"통합 비용 발견",c2:"사용량 기반 배분",c3:"낭비 탐지 및 최적화",c4:"변경-비용 상관관계",c5:"예측 및 예산 가드레일",i1:["온프레 인프라 비용 모델링","클라우드 비용 수집 (AWS, Azure, GCP)","하이브리드 환경 표준화","환경 분리 (prod/dev)"],i2:["CPU/메모리/디스크/네트워크 비용 매핑","애플리케이션 단위 비용 배분","팀/프로젝트/사업부 할당","서비스/워크로드 태깅"],i3:["유휴/저활용 리소스","과다 프로비저닝 compute/storage","좀비 서비스와 고아 자산","중복 환경과 미사용 snapshot"],i4:["배포/구성 변경의 비용 영향","스케일 이벤트 연계 스파이크 탐지","drift로 인한 비용 증가","rollback 비용 검증"],i5:["추세 기반 비용 예측","예산 임계치와 알림","예상치 못한 지출 이상 탐지","스케일링 의사결정을 위한 what-if 분석"],extra:[{title:"Finance 및 FinOps",sub:"예산 통제, 예측, 책임성."},{title:"플랫폼 및 인프라",sub:"Right-sizing 및 낭비 절감."},{title:"엔지니어링 리더십",sub:"비용 인지형 아키텍처 의사결정."},{title:"경영진",sub:"ROI 가시성과 인프라 효율성."}]})
const COST_HI = cost("लागत","ऑप्टिमाइजेशन से पहले दृश्यता","FinOps-स्तर की दृश्यता, इन्फ्रास्ट्रक्चर मॉनिटरिंग में मूल रूप से एकीकृत।","Opticini लागत ऑन-प्रेम, हाइब्रिड और क्लाउड में इन्फ्रास्ट्रक्चर खर्च की रीयल-टाइम और ऐतिहासिक दृश्यता देता है।","यह उपयोग, कॉन्फ़िगरेशन और प्रदर्शन को वित्तीय प्रभाव से जोड़ता है ताकि Finance, IT और Engineering एक ही सत्य स्रोत से निर्णय लें।","मुख्य क्षमताएं","खर्च से वेस्ट और ऑप्टिमाइजेशन तक, एक ही जगह","परिणाम","इन्फ्रास्ट्रक्चर खर्च उद्देश्यपूर्ण, दृश्यमान और बचाव-योग्य बनता है, वास्तविक कार्यों से मापनीय बचत के साथ।","उपयोग को वित्तीय स्पष्टता में बदलें","देखें हर राशि कहां जा रही है और खर्च को प्रदर्शन, बदलाव और जोखिम से जोड़ें।","किसके लिए","सभी हितधारकों के लिए साझा एक लागत दृश्य",{c1:"एकीकृत लागत खोज",c2:"उपयोग-आधारित आवंटन",c3:"वेस्ट डिटेक्शन और ऑप्टिमाइजेशन",c4:"बदलाव-से-लागत सहसंबंध",c5:"पूर्वानुमान और बजट गार्डरेल",i1:["ऑन-प्रेम इन्फ्रास्ट्रक्चर लागत मॉडलिंग","क्लाउड लागत इनजेशन (AWS, Azure, GCP)","हाइब्रिड वातावरण सामान्यीकरण","पर्यावरण विभाजन (prod/dev)"],i2:["CPU, मेमोरी, डिस्क और नेटवर्क लागत मैपिंग","एप्लिकेशन-स्तरीय लागत आवंटन","टीम, प्रोजेक्ट और बिजनेस यूनिट आवंटन","सेवा और वर्कलोड टैगिंग"],i3:["निष्क्रिय/कम उपयोग संसाधन","ओवरप्रोविजन compute और storage","ज़ॉम्बी सेवाएं और orphan assets","रेडंडेंट वातावरण और unused snapshots"],i4:["डिप्लॉय और कॉन्फ़िग बदलाव का लागत प्रभाव","स्केलिंग इवेंट से जुड़े स्पाइक डिटेक्शन","drift-आधारित लागत वृद्धि","rollback लागत सत्यापन"],i5:["ट्रेंड-आधारित लागत पूर्वानुमान","बजट थ्रेशहोल्ड और अलर्ट","अप्रत्याशित खर्च विसंगति पहचान","स्केलिंग निर्णयों के लिए what-if विश्लेषण"],extra:[{title:"Finance और FinOps",sub:"बजट नियंत्रण, पूर्वानुमान और जवाबदेही।"},{title:"प्लेटफ़ॉर्म और इन्फ्रास्ट्रक्चर",sub:"Right-sizing और वेस्ट में कमी।"},{title:"Engineering नेतृत्व",sub:"लागत-सचेत आर्किटेक्चर निर्णय।"},{title:"प्रबंधन",sub:"ROI दृश्यता और इन्फ्रास्ट्रक्चर दक्षता।"}]})
const COST_AR = cost("التكلفة","رؤية قبل التحسين","رؤية بمستوى FinOps مدمجة اصلا في مراقبة البنية التحتية.","يوفر Opticini التكلفة رؤية لحظية وتاريخية لانفاق البنية عبر المحلي والهجين والسحابة.","يربط الاستخدام والتهيئة والاداء بالتأثير المالي لكي تتخذ Finance وIT وEngineering قرارات من مصدر حقيقة واحد.","القدرات الاساسية","من الانفاق الى الهدر الى التحسين في مكان واحد","النتيجة","يصبح انفاق البنية مقصودا ومرئيا وقابلا للدفاع مع وفورات قابلة للقياس مرتبطة باجراءات فعلية.","حوّل الاستخدام الى وضوح مالي","اعرف اين يذهب كل مبلغ واربط الانفاق بالاداء والتغيير والمخاطر.","لمن هذا","رؤية تكلفة واحدة مشتركة بين كل اصحاب المصلحة",{c1:"اكتشاف تكلفة موحد",c2:"اسناد قائم على الاستخدام",c3:"كشف الهدر والتحسين",c4:"ارتباط التغيير بالتكلفة",c5:"التنبؤ وحواجز الميزانية",i1:["نمذجة تكلفة للبنية المحلية","استيعاب تكاليف السحابة (AWS, Azure, GCP)","توحيد البيئات الهجينة","تقسيم حسب البيئة (prod/dev)"],i2:["رسم تكلفة CPU والذاكرة والقرص والشبكة","اسناد تكلفة على مستوى التطبيق","توزيع حسب الفريق والمشروع ووحدة الاعمال","وسم الخدمات واحمال العمل"],i3:["موارد خاملة او منخفضة الاستخدام","Compute وStorage مفرطا التخصيص","خدمات زومبي واصول يتيمة","بيئات مكررة وSnapshots غير مستخدمة"],i4:["تأثير تكلفة عمليات النشر وتغييرات التهيئة","كشف القفزات المرتبطة باحداث التوسع","زيادات تكلفة مدفوعة بـ drift","التحقق من تكلفة rollback"],i5:["تنبؤ بالتكلفة قائم على الاتجاه","حدود ميزانية وتنبيهات","كشف شذوذ الانفاق غير المتوقع","تحليل what-if لقرارات التوسع"],extra:[{title:"Finance وFinOps",sub:"تحكم بالميزانية، تنبؤ، ومساءلة."},{title:"المنصة والبنية التحتية",sub:"Right-sizing وتقليل الهدر."},{title:"قيادة Engineering",sub:"قرارات معمارية واعية بالتكلفة."},{title:"الادارة التنفيذية",sub:"رؤية ROI وكفاءة البنية."}]})
const COST_HE = cost("עלות","נראות לפני אופטימיזציה","נראות ברמת FinOps משולבת באופן טבעי בניטור תשתיות.","Opticini עלות מספק נראות בזמן אמת ובהיסטוריה להוצאות תשתית ב-on-prem, היברידי וענן.","הוא מחבר שימוש, תצורה וביצועים להשפעה פיננסית כדי ש-Finance, IT ו-Engineering יחליטו על בסיס מקור אמת אחד.","יכולות ליבה","מהוצאה לבזבוז ולאופטימיזציה במקום אחד","תוצאה","הוצאות תשתית הופכות מכוונות, נראות וברות הצדקה עם חיסכון מדיד שמחובר לפעולות אמיתיות.","להפוך שימוש לבהירות פיננסית","לראות לאן כל סכום הולך ולקשור הוצאה לביצועים, שינוי וסיכון.","למי זה מיועד","תמונת עלות אחת משותפת לכל בעלי העניין",{c1:"גילוי עלויות מאוחד",c2:"שיוך מבוסס שימוש",c3:"זיהוי בזבוז ואופטימיזציה",c4:"קורלציה בין שינוי לעלות",c5:"חיזוי ומעקות תקציב",i1:["מודל עלות לתשתית מקומית","קליטת עלויות ענן (AWS, Azure, GCP)","נרמול סביבות היברידיות","פילוח לפי סביבה (prod/dev)"],i2:["מיפוי עלויות CPU, זיכרון, דיסק ורשת","שיוך עלויות ברמת אפליקציה","הקצאה לפי צוות, פרויקט ויחידה עסקית","תיוג שירותים ועומסי עבודה"],i3:["משאבים לא פעילים/תת-מנוצלים","Compute ו-Storage בהקצאת יתר","שירותי זומבי ונכסים יתומים","סביבות כפולות ו-Snapshots לא בשימוש"],i4:["השפעת עלות של פריסות ושינויי תצורה","זיהוי קפיצות הקשורות לאירועי סקיילינג","עליות עלות מונעות drift","אימות עלות rollback"],i5:["חיזוי עלות מבוסס מגמה","ספי תקציב והתראות","זיהוי אנומליות בהוצאה בלתי צפויה","ניתוח what-if להחלטות סקיילינג"],extra:[{title:"Finance ו-FinOps",sub:"שליטה בתקציב, חיזוי ואחריותיות."},{title:"פלטפורמה ותשתית",sub:"Right-sizing והפחתת בזבוז."},{title:"הנהגת Engineering",sub:"החלטות ארכיטקטורה מודעות עלות."},{title:"הנהלה",sub:"נראות ROI ויעילות תשתית."}]})

export const COST_PAGE_PATCH_BY_LANG: Record<string, CostPagePatch> = {
  en: { features: { cost: COST_EN } },
  es: { features: { cost: COST_ES } },
  fr: { features: { cost: COST_FR } },
  de: { features: { cost: COST_DE } },
  it: { features: { cost: COST_IT } },
  pt: { features: { cost: COST_PT } },
  ru: { features: { cost: COST_RU } },
  sv: { features: { cost: COST_SV } },
  no: { features: { cost: COST_NO } },
  da: { features: { cost: COST_DA } },
  zh: { features: { cost: COST_ZH } },
  ja: { features: { cost: COST_JA } },
  ko: { features: { cost: COST_KO } },
  hi: { features: { cost: COST_HI } },
  ar: { features: { cost: COST_AR } },
  he: { features: { cost: COST_HE } },
}
