import type { FeatureDetailConfig } from "@/components/feature-detail-page"

type RiskI18nPayload = Omit<FeatureDetailConfig, "colors">
type RiskPagePatch = { features: { risk: RiskI18nPayload } }

function r(
  title: string,
  subtitle: string,
  tagline: string,
  posStrong: string,
  posBody: string,
  sectionLabel: string,
  sectionTitle: string,
  outcomeLabel: string,
  outcomeText: string,
  ctaTitle: string,
  ctaSubtitle: string,
  extraLabel: string,
  extraTitle: string,
  cards: {
    c1: string; c2: string; c3: string; c4: string; c5: string; c6: string;
    i1: string[]; i2: string[]; i3: string[]; i4: string[]; i5: string[]; i6: string[];
    mini: { title: string; sub: string }[];
  }
): RiskI18nPayload {
  return {
    title,
    subtitle,
    tagline,
    planeNum: 10,
    stats: [
      { value: "Unified", label: "risk scoring" },
      { value: "Business", label: "impact mapping" },
      { value: "Executive", label: "risk views" },
      { value: "Synthesis", label: "across all planes" },
    ],
    posStrong,
    posBody,
    sectionLabel,
    sectionTitle,
    cards: [
      { icon: "📊", title: cards.c1, items: cards.i1 },
      { icon: "⚙️", title: cards.c2, items: cards.i2 },
      { icon: "🔒", title: cards.c3, items: cards.i3 },
      { icon: "📋", title: cards.c4, items: cards.i4 },
      { icon: "🔄", title: cards.c5, items: cards.i5 },
      { icon: "💸", title: cards.c6, items: cards.i6 },
    ],
    compareLabel: "",
    compareTitle: "",
    compareOld: "",
    compareNew: "",
    compareRows: [],
    outcomeLabel,
    outcomeText,
    ctaTitle,
    ctaSubtitle,
    extraSection: {
      label: extraLabel,
      title: extraTitle,
      miniCards: cards.mini,
    },
  }
}

const RISK_EN = r(
  "Risk",
  "Continuous awareness of what could break, expose, or cost you",
  "Not all alerts are equal. Risk shows what actually matters and what to fix first.",
  "Opticini Risk provides a unified real-time view of operational, security, compliance, and financial risk.",
  "Instead of siloed alerts and static assessments, Risk continuously evaluates how health, configuration, change, and cost interact to create exposure.",
  "Core Capabilities",
  "Six dimensions of risk unified in one view",
  "Outcome",
  "Fewer outages, earlier detection of systemic weaknesses, and better remediation prioritization.",
  "See risk before it becomes an incident",
  "Unified risk intelligence across all insight planes prioritized by business impact.",
  "The Synthesis Layer",
  "Risk draws signal from every other insight plane",
  {
    c1: "Unified Risk Scoring",
    c2: "Operational Risk Detection",
    c3: "Security Risk Visibility",
    c4: "Compliance and Policy Risk",
    c5: "Change-Induced Risk",
    c6: "Financial and Cost Risk",
    i1: [
      "Asset-level risk scores",
      "Environment-based aggregation",
      "Business impact weighting",
      "Normalized across on-prem, hybrid, and cloud",
    ],
    i2: [
      "Health degradation trends",
      "Capacity exhaustion risk",
      "Single points of failure",
      "SLA and uptime risk modeling",
    ],
    i3: [
      "Exposure from misconfigurations",
      "Unpatched or vulnerable components",
      "Excessive permissions and access sprawl",
      "Public exposure risk",
    ],
    i4: [
      "Drift from compliance baselines",
      "Evidence gaps and audit-readiness risk",
      "Policy violations over time",
      "Control degradation tracking",
    ],
    i5: [
      "Risk from deployments and config changes",
      "High-risk changes without rollback paths",
      "Change velocity versus incident probability",
      "Risk reduction after remediation",
    ],
    i6: [
      "Runaway spend risk detection",
      "Budget threshold breach likelihood",
      "Cost exposure tied to performance issues",
      "Waste accumulation risk over time",
    ],
    mini: [
      { title: "Discovery", sub: "what exists" },
      { title: "Health", sub: "what is degrading" },
      { title: "Performance", sub: "what is stressed" },
      { title: "Security", sub: "what is exposed" },
      { title: "Configuration", sub: "what is misaligned" },
      { title: "Compliance", sub: "what is drifting" },
      { title: "Evidence", sub: "what is unproven" },
      { title: "Change", sub: "what was introduced" },
      { title: "Cost", sub: "what could escalate" },
      { title: "Risk", sub: "what to fix first" },
    ],
  }
)

const RISK_PT = r("Risco","Consciencia continua do que pode quebrar, expor ou custar","Nem todo alerta tem o mesmo peso. Risco mostra o que realmente importa e o que corrigir primeiro.","O plano de Risco do Opticini oferece visao unificada em tempo real de risco operacional, seguranca, compliance e financeiro.","Em vez de alertas em silos e avaliacoes estaticas, Risco avalia continuamente como saude, configuracao, mudanca e custo interagem para gerar exposicao.","Capacidades principais","Seis dimensoes de risco unificadas em uma so visao","Resultado","Menos indisponibilidade, deteccao antecipada de fraquezas sistemicas e melhor priorizacao de remediacao.","Veja o risco antes de virar incidente","Inteligencia de risco unificada em todos os planos de insight, priorizada por impacto de negocio.","Camada de Sintese","Risco puxa sinal de todos os outros planos de insight",{c1:"Pontuacao Unificada de Risco",c2:"Deteccao de Risco Operacional",c3:"Visibilidade de Risco de Seguranca",c4:"Risco de Compliance e Politicas",c5:"Risco Induzido por Mudanca",c6:"Risco Financeiro e de Custo",i1:["Pontuacao de risco por ativo","Agregacao por ambiente","Peso por impacto de negocio","Normalizado entre on-prem, hibrido e nuvem"],i2:["Tendencias de degradacao de saude","Risco de exaustao de capacidade","Pontos unicos de falha","Modelagem de risco de SLA e uptime"],i3:["Exposicao por misconfiguracao","Componentes vulneraveis ou sem patch","Permissoes excessivas e proliferacao de acesso","Risco de exposicao publica"],i4:["Drift de baselines de compliance","Lacunas de evidencias e risco de prontidao para auditoria","Violacoes de politica ao longo do tempo","Acompanhamento de degradacao de controles"],i5:["Risco de deploys e mudancas de configuracao","Mudancas de alto risco sem caminho de rollback","Velocidade de mudanca versus probabilidade de incidente","Reducao de risco apos remediacao"],i6:["Deteccao de risco de gasto fora de controle","Probabilidade de romper limite de orcamento","Exposicao de custo ligada a problemas de desempenho","Risco de acumulacao de desperdicio ao longo do tempo"],mini:[{title:"Discovery",sub:"o que existe"},{title:"Health",sub:"o que esta degradando"},{title:"Performance",sub:"o que esta sob estresse"},{title:"Security",sub:"o que esta exposto"},{title:"Configuration",sub:"o que esta desalinhado"},{title:"Compliance",sub:"o que esta em drift"},{title:"Evidence",sub:"o que nao esta comprovado"},{title:"Change",sub:"o que foi introduzido"},{title:"Cost",sub:"o que pode escalar"},{title:"Risk",sub:"o que corrigir primeiro"}]})
const RISK_ES = r("Riesgo","Conciencia continua de lo que puede fallar, exponerte o costarte","No todas las alertas valen lo mismo. Riesgo muestra que importa de verdad y que corregir primero.","Opticini Riesgo ofrece una vista unificada en tiempo real del riesgo operativo, seguridad, cumplimiento y financiero.","En lugar de alertas en silos, Riesgo evalua continuamente como salud, configuracion, cambio y costo interactuan para crear exposicion.","Capacidades clave","Seis dimensiones de riesgo unificadas en una sola vista","Resultado","Menos caidas, deteccion temprana de debilidades sistemicas y mejor priorizacion de remediacion.","Ve el riesgo antes del incidente","Inteligencia de riesgo unificada en todos los planos de insight, priorizada por impacto de negocio.","Capa de sintesis","Riesgo toma senal de todos los demas planos",{c1:"Puntuacion unificada de riesgo",c2:"Deteccion de riesgo operacional",c3:"Visibilidad de riesgo de seguridad",c4:"Riesgo de cumplimiento y politica",c5:"Riesgo inducido por cambio",c6:"Riesgo financiero y de costo",i1:["Puntuacion por activo","Agregacion por entorno","Peso por impacto de negocio","Normalizado en on-prem, hibrido y nube"],i2:["Tendencias de degradacion de salud","Riesgo de agotamiento de capacidad","Puntos unicos de falla","Modelado de riesgo SLA y uptime"],i3:["Exposicion por mala configuracion","Componentes vulnerables o sin parche","Permisos excesivos y dispersion de acceso","Riesgo de exposicion publica"],i4:["Drift de baselines de cumplimiento","Brechas de evidencia y riesgo de auditoria","Violaciones de politica en el tiempo","Seguimiento de degradacion de controles"],i5:["Riesgo por despliegues y cambios de config","Cambios de alto riesgo sin rollback","Velocidad de cambio vs probabilidad de incidente","Reduccion de riesgo tras remediacion"],i6:["Deteccion de gasto descontrolado","Probabilidad de romper umbral de presupuesto","Exposicion de costo ligada a rendimiento","Riesgo de acumulacion de desperdicio"],mini:[{title:"Discovery",sub:"que existe"},{title:"Health",sub:"que se degrada"},{title:"Performance",sub:"que esta bajo estres"},{title:"Security",sub:"que esta expuesto"},{title:"Configuration",sub:"que esta desalineado"},{title:"Compliance",sub:"que esta en drift"},{title:"Evidence",sub:"que no esta probado"},{title:"Change",sub:"que se introdujo"},{title:"Cost",sub:"que puede escalar"},{title:"Risk",sub:"que corregir primero"}]})
const RISK_FR = r("Risque","Vision continue de ce qui peut casser, exposer ou couter","Toutes les alertes ne se valent pas. Risque montre ce qui compte vraiment et quoi corriger d'abord.","Opticini Risque fournit une vue unifiee en temps reel des risques operationnels, securite, conformite et financiers.","Au lieu d'alertes en silos, Risque evalue en continu l'interaction entre sante, configuration, changement et cout.","Capacites principales","Six dimensions de risque unifiees en une vue","Resultat","Moins de pannes, detection plus precoce des faiblesses systemiques et meilleure priorisation de remediation.","Voir le risque avant l'incident","Intelligence risque unifiee sur tous les plans d'insight, priorisee par impact business.","Couche de synthese","Risque exploite les signaux de tous les autres plans",{c1:"Scoring unifie du risque",c2:"Detection du risque operationnel",c3:"Visibilite du risque securite",c4:"Risque conformite et politique",c5:"Risque induit par le changement",c6:"Risque financier et cout",i1:["Scores de risque par actif","Aggregation par environnement","Ponderation impact business","Normalise on-prem, hybride, cloud"],i2:["Tendances de degradation de sante","Risque d'epuisement de capacite","Points uniques de defaillance","Modelisation risque SLA et uptime"],i3:["Exposition due aux mauvaises configurations","Composants vulnerables/non patches","Permissions excessives et etalement d'acces","Risque d'exposition publique"],i4:["Drift des baselines conformite","Lacunes de preuves et risque d'audit","Violations de politique dans le temps","Suivi degradation des controles"],i5:["Risque des deploiements et changements config","Changements a haut risque sans rollback","Vitesse de changement vs probabilite d'incident","Reduction du risque apres remediation"],i6:["Detection de depenses hors controle","Probabilite de depassement budget","Exposition cout liee aux problemes de performance","Risque d'accumulation de gaspillage"],mini:[{title:"Discovery",sub:"ce qui existe"},{title:"Health",sub:"ce qui se degrade"},{title:"Performance",sub:"ce qui est sous stress"},{title:"Security",sub:"ce qui est expose"},{title:"Configuration",sub:"ce qui est desaligne"},{title:"Compliance",sub:"ce qui derive"},{title:"Evidence",sub:"ce qui n'est pas prouve"},{title:"Change",sub:"ce qui a ete introduit"},{title:"Cost",sub:"ce qui peut escalader"},{title:"Risk",sub:"quoi corriger d'abord"}]})
const RISK_DE = r("Risiko","Kontinuierliches Bewusstsein fur was ausfallen, exponieren oder kosten kann","Nicht alle Alerts sind gleich. Risiko zeigt was wirklich wichtig ist und was zuerst behoben werden muss.","Opticini Risiko liefert eine einheitliche Echtzeit-Sicht auf operative, sicherheits-, compliance- und finanzielle Risiken.","Statt siloartiger Alerts bewertet Risiko kontinuierlich wie Gesundheit, Konfiguration, Anderung und Kosten zusammenwirken.","Kernfahigkeiten","Sechs Risikodimensionen in einer Ansicht","Ergebnis","Weniger Ausfalle, fruhere Erkennung systemischer Schwachen und bessere Priorisierung der Remediation.","Risiken sehen bevor sie zu Incidents werden","Einheitliche Risiko-Intelligenz uber alle Insight-Planes, priorisiert nach Business-Impact.","Synthese-Ebene","Risiko zieht Signale aus allen anderen Insight-Planes",{c1:"Einheitliches Risiko-Scoring",c2:"Erkennung operativer Risiken",c3:"Sichtbarkeit von Sicherheitsrisiken",c4:"Compliance- und Policy-Risiko",c5:"Anderungsinduziertes Risiko",c6:"Finanz- und Kostenrisiko",i1:["Risikoscores auf Asset-Ebene","Aggregation nach Umgebung","Gewichtung nach Business-Impact","Normalisiert uber on-prem, hybrid und cloud"],i2:["Trends bei Gesundheitsverschlechterung","Risiko von Kapazitatserschopfung","Single Points of Failure","SLA- und Uptime-Risikomodellierung"],i3:["Exposition durch Fehlkonfigurationen","Ungepatchte oder verwundbare Komponenten","Ubermassige Berechtigungen und Access-Sprawl","Risiko offentlicher Exposition"],i4:["Drift von Compliance-Baselines","Evidenzlucken und Audit-Bereitschaftsrisiko","Policy-Verletzungen uber die Zeit","Tracking von Kontrollverschlechterung"],i5:["Risiko durch Deployments und Konfig-Anderungen","Hochrisiko-Anderungen ohne Rollback-Pfad","Anderungsgeschwindigkeit vs Incident-Wahrscheinlichkeit","Risikoreduktion nach Remediation"],i6:["Erkennung von unkontrolliertem Ausgabenrisiko","Wahrscheinlichkeit von Budgetgrenzen-Uberschreitung","Kostenexposition durch Performanceprobleme","Risiko der Verschwendungsakkumulation"],mini:[{title:"Discovery",sub:"was existiert"},{title:"Health",sub:"was sich verschlechtert"},{title:"Performance",sub:"was unter Last steht"},{title:"Security",sub:"was exponiert ist"},{title:"Configuration",sub:"was fehljustiert ist"},{title:"Compliance",sub:"was driftet"},{title:"Evidence",sub:"was unbewiesen ist"},{title:"Change",sub:"was eingefuhrt wurde"},{title:"Cost",sub:"was eskalieren kann"},{title:"Risk",sub:"was zuerst zu beheben ist"}]})
const RISK_IT = r("Rischio","Consapevolezza continua di cosa puo rompersi, esporre o costare","Non tutti gli alert sono uguali. Rischio mostra cosa conta davvero e cosa correggere prima.","Opticini Rischio offre una vista unificata in tempo reale del rischio operativo, sicurezza, compliance e finanziario.","Invece di alert a silos, Rischio valuta continuamente come salute, configurazione, cambiamento e costo interagiscono.","Capacita principali","Sei dimensioni di rischio unificate in un'unica vista","Risultato","Meno disservizi, rilevazione anticipata di debolezze sistemiche e migliore priorizzazione della remediation.","Vedi il rischio prima dell'incidente","Intelligenza di rischio unificata su tutti gli insight plane, priorizzata per impatto business.","Layer di sintesi","Rischio attinge segnali da tutti gli altri piani",{c1:"Scoring rischio unificato",c2:"Rilevazione rischio operativo",c3:"Visibilita rischio sicurezza",c4:"Rischio compliance e policy",c5:"Rischio indotto dal cambiamento",c6:"Rischio finanziario e costo",i1:["Score di rischio per asset","Aggregazione per ambiente","Ponderazione per impatto business","Normalizzato su on-prem, ibrido e cloud"],i2:["Trend di degrado della salute","Rischio esaurimento capacita","Single point of failure","Modellazione rischio SLA e uptime"],i3:["Esposizione da misconfigurazioni","Componenti vulnerabili o non patchati","Permessi eccessivi e sprawl di accesso","Rischio di esposizione pubblica"],i4:["Drift dalle baseline di compliance","Gap di evidenze e rischio audit readiness","Violazioni di policy nel tempo","Tracking del degrado dei controlli"],i5:["Rischio da deploy e cambi config","Cambi ad alto rischio senza rollback","Velocita di cambiamento vs probabilita incidente","Riduzione rischio dopo remediation"],i6:["Rilevazione rischio spesa fuori controllo","Probabilita superamento soglia budget","Esposizione costi legata a performance","Rischio accumulo sprechi nel tempo"],mini:[{title:"Discovery",sub:"cosa esiste"},{title:"Health",sub:"cosa degrada"},{title:"Performance",sub:"cosa e sotto stress"},{title:"Security",sub:"cosa e esposto"},{title:"Configuration",sub:"cosa e disallineato"},{title:"Compliance",sub:"cosa e in drift"},{title:"Evidence",sub:"cosa non e provato"},{title:"Change",sub:"cosa e stato introdotto"},{title:"Cost",sub:"cosa puo scalare"},{title:"Risk",sub:"cosa correggere prima"}]})
const RISK_RU = r("Риск","Непрерывное понимание того что может сломаться, открыть уязвимость или увеличить затраты","Не все алерты равны. Риск показывает что действительно важно и что исправлять в первую очередь.","Opticini Риск дает единую картину в реальном времени по операционным, security, compliance и финансовым рискам.","Вместо разрозненных алертов Риск непрерывно оценивает как здоровье, конфигурация, изменения и стоимость формируют экспозицию.","Ключевые возможности","Шесть измерений риска в единой картине","Результат","Меньше сбоев, более раннее выявление системных слабостей и лучшая приоритизация remediation.","Увидеть риск до инцидента","Единая риск-аналитика по всем insight plane с приоритетом по business impact.","Слой синтеза","Риск берет сигналы из всех остальных plane",{c1:"Единый скоринг риска",c2:"Выявление операционного риска",c3:"Видимость рисков безопасности",c4:"Риск compliance и policy",c5:"Риск, вызванный изменениями",c6:"Финансовый и cost риск",i1:["Риск-скор на уровне актива","Агрегация по средам","Вес по бизнес-воздействию","Нормализация для on-prem, hybrid, cloud"],i2:["Тренды деградации здоровья","Риск исчерпания мощности","Единые точки отказа","Моделирование SLA/uptime риска"],i3:["Экспозиция из-за misconfiguration","Непатченные или уязвимые компоненты","Избыточные права и access sprawl","Риск публичной экспозиции"],i4:["Drift от baseline соответствия","Пробелы в evidence и риск готовности к аудиту","Нарушения policy во времени","Отслеживание деградации контролей"],i5:["Риск из-за deploy и config-изменений","Высокорискованные изменения без rollback","Скорость изменений vs вероятность инцидента","Снижение риска после remediation"],i6:["Выявление риска runaway spend","Вероятность пробития budget threshold","Cost exposure, связанный с performance проблемами","Риск накопления waste со временем"],mini:[{title:"Discovery",sub:"что существует"},{title:"Health",sub:"что деградирует"},{title:"Performance",sub:"что под нагрузкой"},{title:"Security",sub:"что экспонировано"},{title:"Configuration",sub:"что не выровнено"},{title:"Compliance",sub:"что уходит в drift"},{title:"Evidence",sub:"что не доказано"},{title:"Change",sub:"что было внесено"},{title:"Cost",sub:"что может эскалировать"},{title:"Risk",sub:"что исправить первым"}]})
const RISK_SV = r("Risk","Kontinuerlig medvetenhet om vad som kan ga sonder, exponera eller kosta","Alla larm ar inte lika viktiga. Risk visar vad som faktiskt spelar roll och vad som ska atgardas forst.","Opticini Risk ger en enhetlig realtidsbild av operativ, sakerhets-, compliance- och finansiell risk.","Istallet for silo-larm utvarderar Risk kontinuerligt hur halsa, konfiguration, andring och kostnad samverkar.","Karnfunktioner","Sex riskdimensioner i en och samma vy","Resultat","Farre avbrott, tidigare upptackt av systemiska svagheter och battre prioritering av atgard.","Se risk innan den blir incident","Enhetlig riskintelligens over alla insight-plan prioriterad efter affarspaverkan.","Synteslager","Risk drar signaler fran alla andra plan",{c1:"Enhetlig riskscoring",c2:"Detektion av operativ risk",c3:"Synlighet i sakerhetsrisk",c4:"Compliance- och policyrisk",c5:"Andringsinducerad risk",c6:"Finansiell och kostnadsrisk",i1:["Riskscore per tillgang","Aggregation per miljo","Viktning efter affarspaverkan","Normaliserad over on-prem, hybrid och moln"],i2:["Trender i halsodegradering","Risk for kapacitetsutarmning","Single points of failure","SLA- och uptime-riskmodellering"],i3:["Exponering fran felkonfiguration","Opatchade eller sarbara komponenter","Overdrivna behorigheter och access-sprawl","Risk for publik exponering"],i4:["Drift fran compliance-baselines","Evidensluckor och audit-readiness-risk","Policybrott over tid","Spårning av kontrollforringring"],i5:["Risk fran deploys och config-andringar","Hogriskandringar utan rollback-vag","Andringstakt vs incident-sannolikhet","Riskreduktion efter atgard"],i6:["Detektion av runaway spend-risk","Sannolikhet att overskrida budgetniva","Kostnadsexponering kopplad till prestandaproblem","Risk for ackumulerat sloseri over tid"],mini:[{title:"Discovery",sub:"vad som finns"},{title:"Health",sub:"vad som degraderas"},{title:"Performance",sub:"vad som ar under stress"},{title:"Security",sub:"vad som ar exponerat"},{title:"Configuration",sub:"vad som ar feljusterat"},{title:"Compliance",sub:"vad som driftar"},{title:"Evidence",sub:"vad som saknar bevis"},{title:"Change",sub:"vad som introducerades"},{title:"Cost",sub:"vad som kan eskalera"},{title:"Risk",sub:"vad som fixas forst"}]})
const RISK_NO = r("Risiko","Kontinuerlig bevissthet om hva som kan bryte, eksponere eller koste","Ikke alle varsler er like. Risiko viser hva som faktisk betyr noe og hva som ma fikses forst.","Opticini Risiko gir en samlet sanntidsvisning av operasjonell, sikkerhets-, compliance- og finansiell risiko.","I stedet for silo-varsler evaluerer Risiko kontinuerlig hvordan helse, konfigurasjon, endring og kostnad samvirker.","Kjernekapabiliteter","Seks risikodimensjoner samlet i ett bilde","Resultat","Faerre nedetider, tidligere oppdagelse av systemiske svakheter og bedre prioritering av remediation.","Se risiko for den blir incident","Samlet risikointelligens over alle insight-plan prioritert etter business impact.","Synteselag","Risiko henter signaler fra alle andre plan",{c1:"Samlet risikoscoring",c2:"Deteksjon av operasjonell risiko",c3:"Synlighet i sikkerhetsrisiko",c4:"Compliance- og policy-risiko",c5:"Endringsindusert risiko",c6:"Finansiell og kostnadsrisiko",i1:["Risikoscore per eiendel","Aggregasjon per miljo","Vekting etter business impact","Normalisert over on-prem, hybrid og sky"],i2:["Trender i helsedegradering","Risiko for kapasitetsuttomming","Single points of failure","SLA- og uptime-risikomodellering"],i3:["Eksponering fra feilkonfigurasjoner","Upatchede eller sarbare komponenter","Overdrevne tillatelser og access-sprawl","Risiko for offentlig eksponering"],i4:["Drift fra compliance-baselines","Evidensgap og audit-readiness-risiko","Policybrudd over tid","Sporing av kontrollforringelse"],i5:["Risiko fra deploys og config-endringer","Hoyrisiko-endringer uten rollback-lop","Endringshastighet vs incident-sannsynlighet","Risikoreduksjon etter remediation"],i6:["Deteksjon av runaway spend-risiko","Sannsynlighet for budsjettterskelbrudd","Kostnadseksponering koblet til ytelsesproblemer","Risiko for akkumulert slosing over tid"],mini:[{title:"Discovery",sub:"hva som finnes"},{title:"Health",sub:"hva som degraderes"},{title:"Performance",sub:"hva som er under stress"},{title:"Security",sub:"hva som er eksponert"},{title:"Configuration",sub:"hva som er feiljustert"},{title:"Compliance",sub:"hva som driftes"},{title:"Evidence",sub:"hva som ikke er bevist"},{title:"Change",sub:"hva som ble introdusert"},{title:"Cost",sub:"hva som kan eskalere"},{title:"Risk",sub:"hva som fikses forst"}]})
const RISK_DA = r("Risiko","Kontinuerlig bevidsthed om hvad der kan bryde, eksponere eller koste","Ikke alle alarmer er lige vigtige. Risiko viser hvad der faktisk betyder noget og hvad der skal fixes forst.","Opticini Risiko giver en samlet realtidsvisning af operationel, sikkerheds-, compliance- og finansiel risiko.","I stedet for silo-alarmer evaluerer Risiko kontinuerligt hvordan helse, konfiguration, andring og omkostning spiller sammen.","Kernekapabiliteter","Seks risikodimensioner samlet i en visning","Resultat","Faerre nedbrud, tidligere opdagelse af systemiske svagheder og bedre prioritering af remediation.","Se risiko for den bliver incident","Samlet risiko-intelligens pa tvrs af alle insight-plan prioriteret efter business impact.","Synteselag","Risiko henter signaler fra alle andre plan",{c1:"Samlet risikoscoring",c2:"Detektion af operationel risiko",c3:"Synlighed i sikkerhedsrisiko",c4:"Compliance- og policy-risiko",c5:"Andringsinduceret risiko",c6:"Finansiel og omkostningsrisiko",i1:["Risikoscore pr. aktiv","Aggregation pr. miljo","Vaegtning efter business impact","Normaliseret pa tvrs af on-prem, hybrid og cloud"],i2:["Trends i helbredsforringelse","Risiko for kapacitetsudtomning","Single points of failure","SLA- og uptime-risikomodellering"],i3:["Eksponering fra fejlkfiguration","Upatchede eller sarbare komponenter","Overdrevne rettigheder og access-sprawl","Risiko for offentlig eksponering"],i4:["Drift fra compliance-baselines","Evidenshuller og audit-readiness-risiko","Policy-overtraedelser over tid","Sporing af kontrolforringelse"],i5:["Risiko fra deploys og config-andringer","Hoyrisiko-andringer uden rollback-vej","Andringshastighed vs incident-sandsynlighed","Risikoreduktion efter remediation"],i6:["Detektion af runaway spend-risiko","Sandsynlighed for budgettaerskelbrud","Kostnadseksponering koblet til performanceproblemer","Risiko for akkumulering af spild over tid"],mini:[{title:"Discovery",sub:"hvad der findes"},{title:"Health",sub:"hvad der degraderes"},{title:"Performance",sub:"hvad der er under pres"},{title:"Security",sub:"hvad der er eksponeret"},{title:"Configuration",sub:"hvad der er fejljusteret"},{title:"Compliance",sub:"hvad der drifter"},{title:"Evidence",sub:"hvad der ikke er bevist"},{title:"Change",sub:"hvad der blev introduceret"},{title:"Cost",sub:"hvad der kan eskalere"},{title:"Risk",sub:"hvad der fikses forst"}]})
const RISK_ZH = r("风险","持续感知什么会出故障、暴露或带来成本","并非所有告警都同样重要。风险告诉你真正重要的事和优先修复项。","Opticini 风险提供运营、安全、合规和财务风险的统一实时视图。","风险不再是孤立告警，而是持续评估健康、配置、变更、成本如何相互作用形成暴露。","核心能力","六大风险维度统一在一个视图中","结果","更少故障，更早发现系统性弱点，更好地进行修复优先级排序。","在风险变成事件前看见它","跨所有 insight plane 的统一风险智能，按业务影响优先级排序。","综合层","风险从其他所有 plane 获取信号",{c1:"统一风险评分",c2:"运营风险检测",c3:"安全风险可视化",c4:"合规与策略风险",c5:"变更诱发风险",c6:"财务与成本风险",i1:["资产级风险评分","按环境聚合","按业务影响加权","跨 on-prem、hybrid、cloud 标准化"],i2:["健康退化趋势","容量耗尽风险","单点故障","SLA 与 uptime 风险建模"],i3:["由错误配置导致的暴露","未打补丁或脆弱组件","过度权限与访问扩散","公网暴露风险"],i4:["偏离合规 baseline 的 drift","证据缺口与审计就绪风险","长期策略违规","控制项退化跟踪"],i5:["由部署与配置变更引发的风险","无 rollback 路径的高风险变更","变更速度与事件概率关系","修复后的风险下降"],i6:["失控支出风险检测","突破预算阈值概率","与性能问题相关的成本暴露","长期浪费累积风险"],mini:[{title:"Discovery",sub:"存在什么"},{title:"Health",sub:"什么在退化"},{title:"Performance",sub:"什么承压"},{title:"Security",sub:"什么被暴露"},{title:"Configuration",sub:"什么失配"},{title:"Compliance",sub:"什么在 drift"},{title:"Evidence",sub:"什么未被证明"},{title:"Change",sub:"引入了什么"},{title:"Cost",sub:"什么可能升级"},{title:"Risk",sub:"先修什么"}]})
const RISK_JA = r("リスク","壊れる・露出する・コスト化する要因を継続把握","すべてのアラートが同じ重要度ではありません。リスクは本当に重要なものを示します。","Opticini リスクは運用・セキュリティ・コンプライアンス・財務リスクを統合してリアルタイムに可視化します。","サイロ化したアラートではなく、ヘルス・構成・変更・コストの相互作用を継続評価して露出を見つけます。","コア機能","6つのリスク次元を1つの視点に統合","結果","障害の削減、構造的弱点の早期検知、修復優先順位の最適化を実現します。","インシデント前にリスクを可視化","全 insight plane を横断する統合リスクインテリジェンスをビジネス影響で優先順位化。","統合レイヤー","リスクは他のすべての plane から信号を取り込みます",{c1:"統合リスクスコアリング",c2:"運用リスク検知",c3:"セキュリティリスク可視化",c4:"コンプライアンス/ポリシーリスク",c5:"変更誘発リスク",c6:"財務/コストリスク",i1:["資産レベルのリスクスコア","環境別集約","ビジネス影響重み付け","on-prem/hybrid/cloud 横断で正規化"],i2:["ヘルス劣化トレンド","容量枯渇リスク","単一障害点","SLA/uplime リスクモデリング"],i3:["誤設定による露出","未パッチ/脆弱コンポーネント","過剰権限とアクセス拡散","公開露出リスク"],i4:["compliance baseline からの drift","証跡ギャップと監査準備リスク","時間経過での policy 違反","コントロール劣化追跡"],i5:["deploy/config 変更由来のリスク","rollback 経路なし高リスク変更","変更速度と incident 確率","remediation 後のリスク低減"],i6:["runaway spend リスク検知","予算閾値超過確率","performance 問題に紐づくコスト露出","時間経過での waste 蓄積リスク"],mini:[{title:"Discovery",sub:"何が存在するか"},{title:"Health",sub:"何が劣化しているか"},{title:"Performance",sub:"何に負荷がかかるか"},{title:"Security",sub:"何が露出しているか"},{title:"Configuration",sub:"何が不整合か"},{title:"Compliance",sub:"何が drift しているか"},{title:"Evidence",sub:"何が未証明か"},{title:"Change",sub:"何が導入されたか"},{title:"Cost",sub:"何が増大し得るか"},{title:"Risk",sub:"何を先に直すか"}]})
const RISK_KO = r("리스크","무엇이 고장나고 노출되며 비용을 키울지 지속 인지","모든 알림이 동일하게 중요하지 않습니다. 리스크는 무엇을 먼저 고쳐야 하는지 보여줍니다.","Opticini 리스크는 운영, 보안, 컴플라이언스, 재무 리스크를 통합해 실시간으로 보여줍니다.","사일로 알림 대신, 헬스/구성/변경/비용의 상호작용을 지속 평가해 노출을 파악합니다.","핵심 기능","6가지 리스크 차원을 하나의 뷰로 통합","결과","장애 감소, 시스템 약점 조기 탐지, remediation 우선순위 최적화를 달성합니다.","인시던트가 되기 전에 리스크 확인","모든 insight plane를 아우르는 통합 리스크 인텔리전스를 비즈니스 영향 기준으로 우선순위화.","합성 레이어","리스크는 다른 모든 plane의 신호를 결합합니다",{c1:"통합 리스크 스코어링",c2:"운영 리스크 탐지",c3:"보안 리스크 가시화",c4:"컴플라이언스/정책 리스크",c5:"변경 유발 리스크",c6:"재무/비용 리스크",i1:["자산 단위 리스크 점수","환경별 집계","비즈니스 영향 가중치","on-prem/hybrid/cloud 정규화"],i2:["헬스 저하 추세","용량 고갈 리스크","단일 장애 지점","SLA/uptime 리스크 모델링"],i3:["오구성으로 인한 노출","미패치/취약 구성요소","과도 권한 및 접근 확산","공개 노출 리스크"],i4:["compliance baseline 대비 drift","증적 공백과 감사 준비 리스크","시간 경과 정책 위반","통제 항목 저하 추적"],i5:["배포/구성 변경 리스크","rollback 경로 없는 고위험 변경","변경 속도와 incident 확률","remediation 이후 리스크 감소"],i6:["runaway spend 리스크 탐지","예산 임계 초과 가능성","performance 문제 연계 비용 노출","시간 경과 waste 누적 리스크"],mini:[{title:"Discovery",sub:"무엇이 존재하는가"},{title:"Health",sub:"무엇이 저하되는가"},{title:"Performance",sub:"무엇이 스트레스를 받는가"},{title:"Security",sub:"무엇이 노출되었는가"},{title:"Configuration",sub:"무엇이 불일치하는가"},{title:"Compliance",sub:"무엇이 drift되는가"},{title:"Evidence",sub:"무엇이 입증되지 않았는가"},{title:"Change",sub:"무엇이 도입되었는가"},{title:"Cost",sub:"무엇이 확대될 수 있는가"},{title:"Risk",sub:"무엇을 먼저 고칠 것인가"}]})
const RISK_HI = r("जोखिम","क्या टूट सकता है, उजागर हो सकता है, या खर्च बढ़ा सकता है—इसकी निरंतर समझ","सभी अलर्ट समान नहीं होते। जोखिम बताता है वास्तव में क्या महत्वपूर्ण है और पहले क्या ठीक करना है।","Opticini जोखिम संचालन, सुरक्षा, अनुपालन और वित्तीय जोखिम का एकीकृत रीयल-टाइम दृश्य देता है।","अलग-अलग अलर्ट के बजाय जोखिम लगातार देखता है कि स्वास्थ्य, कॉन्फ़िगरेशन, बदलाव और लागत कैसे मिलकर एक्सपोज़र बनाते हैं।","मुख्य क्षमताएं","जोखिम की 6 आयामों को एक दृश्य में एकीकृत","परिणाम","कम डाउनटाइम, प्रणालीगत कमजोरियों की जल्दी पहचान और बेहतर remediation प्राथमिकता।","इंसिडेंट बनने से पहले जोखिम देखें","सभी insight plane में एकीकृत जोखिम बुद्धिमत्ता, व्यवसाय प्रभाव के अनुसार प्राथमिकता के साथ।","सिंथेसिस लेयर","जोखिम अन्य सभी planes से संकेत लेता है",{c1:"एकीकृत जोखिम स्कोरिंग",c2:"ऑपरेशनल जोखिम पहचान",c3:"सुरक्षा जोखिम दृश्यता",c4:"अनुपालन और नीति जोखिम",c5:"बदलाव-प्रेरित जोखिम",c6:"वित्तीय और लागत जोखिम",i1:["एसेट-स्तरीय जोखिम स्कोर","पर्यावरण-आधारित समूहीकरण","व्यवसाय प्रभाव वेटिंग","on-prem/hybrid/cloud में सामान्यीकृत"],i2:["स्वास्थ्य गिरावट के ट्रेंड","क्षमता खत्म होने का जोखिम","सिंगल पॉइंट ऑफ फेल्योर","SLA/uptime जोखिम मॉडलिंग"],i3:["गलत कॉन्फ़िगरेशन से एक्सपोज़र","अनपैच्ड/कमजोर घटक","अत्यधिक अनुमति और access sprawl","सार्वजनिक एक्सपोज़र जोखिम"],i4:["अनुपालन baseline से drift","एविडेंस गैप और audit-readiness जोखिम","समय के साथ नीति उल्लंघन","कंट्रोल degradation ट्रैकिंग"],i5:["deploy/config बदलाव से जोखिम","rollback पथ के बिना उच्च जोखिम बदलाव","बदलाव गति बनाम incident संभावना","remediation के बाद जोखिम में कमी"],i6:["runaway spend जोखिम पहचान","बजट सीमा टूटने की संभावना","performance मुद्दों से जुड़ा cost exposure","समय के साथ waste accumulation जोखिम"],mini:[{title:"Discovery",sub:"क्या मौजूद है"},{title:"Health",sub:"क्या degrade हो रहा है"},{title:"Performance",sub:"क्या stress में है"},{title:"Security",sub:"क्या exposed है"},{title:"Configuration",sub:"क्या misaligned है"},{title:"Compliance",sub:"क्या drift कर रहा है"},{title:"Evidence",sub:"क्या unproven है"},{title:"Change",sub:"क्या introduce हुआ"},{title:"Cost",sub:"क्या escalate हो सकता है"},{title:"Risk",sub:"पहले क्या ठीक करें"}]})
const RISK_AR = r("المخاطر","وعي مستمر بما قد يتعطل او ينكشف او يرفع التكلفة","ليست كل التنبيهات متساوية. المخاطر توضح ما يهم فعلا وما يجب اصلاحه اولا.","يوفر Opticini المخاطر رؤية موحدة لحظية لمخاطر التشغيل والامن والامتثال والمالية.","بدلا من تنبيهات متفرقة، يقيم المخاطر باستمرار كيف تتفاعل الصحة والتهيئة والتغيير والتكلفة لتكوين الانكشاف.","القدرات الرئيسية","ستة ابعاد للمخاطر موحدة في عرض واحد","النتيجة","اعطال اقل، اكتشاف ابكر للضعف النظامي، واولوية افضل للمعالجة.","شاهد المخاطر قبل ان تصبح حادثا","ذكاء مخاطر موحد عبر جميع insight planes وباولوية حسب اثر الاعمال.","طبقة التركيب","المخاطر تستمد الاشارات من كل الخطط الاخرى",{c1:"تقييم مخاطر موحد",c2:"كشف مخاطر تشغيلية",c3:"رؤية مخاطر امنية",c4:"مخاطر الامتثال والسياسات",c5:"مخاطر ناتجة عن التغيير",c6:"مخاطر مالية وتكلفة",i1:["درجات مخاطر على مستوى الاصل","تجميع حسب البيئة","ترجيح حسب اثر الاعمال","توحيد عبر on-prem/hybrid/cloud"],i2:["اتجاهات تدهور الصحة","مخاطر نفاد السعة","نقاط فشل مفردة","نمذجة مخاطر SLA وuptime"],i3:["انكشاف ناتج عن سوء التهيئة","مكونات غير مرقعة او ضعيفة","صلاحيات مفرطة وتوسع الوصول","مخاطر الانكشاف العام"],i4:["drift عن baseline الامتثال","فجوات الادلة ومخاطر جاهزية التدقيق","انتهاكات السياسات بمرور الوقت","تتبع تدهور الضوابط"],i5:["مخاطر من النشر وتغييرات التهيئة","تغييرات عالية المخاطر بلا مسار rollback","سرعة التغيير مقابل احتمال incident","انخفاض المخاطر بعد remediation"],i6:["كشف مخاطر runaway spend","احتمال اختراق عتبة الميزانية","انكشاف تكلفة مرتبط بمشاكل الاداء","مخاطر تراكم الهدر بمرور الوقت"],mini:[{title:"Discovery",sub:"ما الموجود"},{title:"Health",sub:"ما الذي يتدهور"},{title:"Performance",sub:"ما تحت الضغط"},{title:"Security",sub:"ما المكشوف"},{title:"Configuration",sub:"ما غير المتسق"},{title:"Compliance",sub:"ما في drift"},{title:"Evidence",sub:"ما غير المثبت"},{title:"Change",sub:"ما تم ادخاله"},{title:"Cost",sub:"ما قد يتصاعد"},{title:"Risk",sub:"ما الذي يصلح اولا"}]})
const RISK_HE = r("סיכון","מודעות רציפה למה שעלול להישבר, להיחשף או לעלות כסף","לא כל ההתראות שוות. סיכון מראה מה באמת חשוב ומה לתקן קודם.","Opticini סיכון מספק תצוגה אחודה בזמן אמת של סיכוני תפעול, אבטחה, תאימות ופיננסים.","במקום התראות סילואיות, סיכון מעריך ברצף כיצד בריאות, תצורה, שינוי ועלות מתחברים לחשיפה.","יכולות ליבה","שישה ממדי סיכון מאוחדים בתצוגה אחת","תוצאה","פחות תקלות, גילוי מוקדם יותר של חולשות מערכתיות ותעדוף טוב יותר ל-remediation.","לראות סיכון לפני שהוא הופך לאירוע","מודיעין סיכונים אחוד בכל insight planes עם תעדוף לפי השפעת עסק.","שכבת סינתזה","סיכון שואב אותות מכל שאר ה-planes",{c1:"דירוג סיכון מאוחד",c2:"זיהוי סיכון תפעולי",c3:"נראות סיכון אבטחה",c4:"סיכון תאימות ומדיניות",c5:"סיכון מושרה שינוי",c6:"סיכון פיננסי ועלות",i1:["ציון סיכון ברמת נכס","אגרגציה לפי סביבה","שקלול לפי השפעה עסקית","נרמול על פני on-prem/hybrid/cloud"],i2:["מגמות הידרדרות בריאות","סיכון למיצוי קיבולת","נקודות כשל בודדות","מודלי סיכון SLA ו-uptime"],i3:["חשיפה מתצורות שגויות","רכיבים פגיעים/לא מתוקנים","הרשאות יתר ו-access sprawl","סיכון חשיפה ציבורית"],i4:["drift מ-baseline תאימות","פערי ראיות וסיכון מוכנות ביקורת","הפרות מדיניות לאורך זמן","מעקב הידרדרות בקרות"],i5:["סיכון מפריסות ושינויי תצורה","שינויים בסיכון גבוה ללא נתיב rollback","מהירות שינוי מול הסתברות incident","הפחתת סיכון אחרי remediation"],i6:["זיהוי סיכון runaway spend","הסתברות לפריצת סף תקציב","חשיפת עלות קשורה לבעיות ביצועים","סיכון לצבירת waste לאורך זמן"],mini:[{title:"Discovery",sub:"מה קיים"},{title:"Health",sub:"מה מידרדר"},{title:"Performance",sub:"מה בלחץ"},{title:"Security",sub:"מה חשוף"},{title:"Configuration",sub:"מה לא מיושר"},{title:"Compliance",sub:"מה ב-drift"},{title:"Evidence",sub:"מה לא מוכח"},{title:"Change",sub:"מה הוכנס"},{title:"Cost",sub:"מה יכול להסלים"},{title:"Risk",sub:"מה לתקן ראשון"}]})

export const RISK_PAGE_PATCH_BY_LANG: Record<string, RiskPagePatch> = {
  en: { features: { risk: RISK_EN } },
  es: { features: { risk: RISK_ES } },
  fr: { features: { risk: RISK_FR } },
  de: { features: { risk: RISK_DE } },
  it: { features: { risk: RISK_IT } },
  pt: { features: { risk: RISK_PT } },
  ru: { features: { risk: RISK_RU } },
  sv: { features: { risk: RISK_SV } },
  no: { features: { risk: RISK_NO } },
  da: { features: { risk: RISK_DA } },
  zh: { features: { risk: RISK_ZH } },
  ja: { features: { risk: RISK_JA } },
  ko: { features: { risk: RISK_KO } },
  hi: { features: { risk: RISK_HI } },
  ar: { features: { risk: RISK_AR } },
  he: { features: { risk: RISK_HE } },
}
