# Generated by Django 5.2.6 on 2026-02-27 02:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('change', '0001_change_schema_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('change_request_id', models.UUIDField(db_index=True)),
                ('approved_by', models.UUIDField()),
            ],
            options={
                'db_table': 'change_approvals',
            },
        ),
        migrations.CreateModel(
            name='ChangeEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_id', models.UUIDField(db_index=True)),
                ('change_type', models.CharField(max_length=64)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('risk_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'change_events',
            },
        ),
        migrations.CreateModel(
            name='ChangeIncidentLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('change_event_id', models.UUIDField(db_index=True)),
                ('incident_id', models.UUIDField(db_index=True)),
            ],
            options={
                'db_table': 'change_incident_links',
            },
        ),
        migrations.CreateModel(
            name='ChangeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=512)),
                ('approval_status', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'change_requests',
            },
        ),
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('application_id', models.UUIDField(db_index=True)),
                ('deployed_at', models.DateTimeField()),
                ('status', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'deployments',
            },
        ),
    ]
