# Generated by Django 5.2.6 on 2026-02-27 02:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('discovery', '0005_asset_signal_and_inventory_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('provider', models.CharField(max_length=64)),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('environment', models.CharField(blank=True, max_length=64)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=32)),
                ('resource_count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_key', models.CharField(blank=True, max_length=128)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=512)),
                ('asset_type', models.CharField(max_length=64)),
                ('environment_id', models.UUIDField(blank=True, null=True)),
                ('lifecycle_state', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('retired', 'Retired'), ('deleted', 'Deleted')], default='active', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(blank=True, max_length=32)),
                ('provider', models.CharField(blank=True, max_length=64)),
                ('account_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_changed_at', models.DateTimeField(blank=True, null=True)),
                ('criticality', models.CharField(blank=True, max_length=32)),
                ('in_scope_soc2', models.BooleanField(default=False)),
                ('scope_flags', models.JSONField(blank=True, null=True)),
                ('owner_display', models.CharField(blank=True, max_length=255)),
                ('attributes_public', models.JSONField(blank=True, null=True)),
                ('attributes_internal', models.JSONField(blank=True, null=True)),
                ('region', models.CharField(blank=True, max_length=128)),
                ('site', models.CharField(blank=True, max_length=128)),
                ('application_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('depends_on_count', models.IntegerField(blank=True, null=True)),
                ('used_by_count', models.IntegerField(blank=True, null=True)),
                ('provider_resource_id', models.CharField(blank=True, max_length=512)),
                ('hostname', models.CharField(blank=True, max_length=512)),
                ('primary_ip', models.CharField(blank=True, max_length=64)),
                ('k8s_cluster', models.CharField(blank=True, max_length=255)),
                ('k8s_namespace', models.CharField(blank=True, max_length=255)),
                ('connector_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('data_classification', models.CharField(blank=True, max_length=64)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('tags_preview', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'assets',
            },
        ),
        migrations.CreateModel(
            name='Connector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('connector_type', models.CharField(max_length=64)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'connectors',
            },
        ),
        migrations.CreateModel(
            name='RawAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.UUIDField(db_index=True)),
                ('connector_id', models.UUIDField(blank=True, null=True)),
                ('external_id', models.CharField(max_length=255)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'raw_assets',
            },
        ),
        migrations.CreateModel(
            name='AssetAttribute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=255)),
                ('value', models.TextField(blank=True)),
                ('asset', models.ForeignKey(db_column='asset_id', on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='discovery.asset')),
            ],
            options={
                'db_table': 'asset_attributes',
            },
        ),
        migrations.CreateModel(
            name='AssetChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('change_type', models.CharField(max_length=64)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('risk_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('asset', models.ForeignKey(db_column='asset_id', on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='discovery.asset')),
            ],
            options={
                'db_table': 'asset_changes',
            },
        ),
        migrations.CreateModel(
            name='AssetOwnership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('technical', 'Technical'), ('business', 'Business')], default='technical', max_length=32)),
                ('team_id', models.UUIDField(blank=True, null=True)),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('asset', models.ForeignKey(db_column='asset_id', on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='discovery.asset')),
            ],
            options={
                'db_table': 'asset_ownership',
            },
        ),
        migrations.CreateModel(
            name='AssetRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relationship_type', models.CharField(max_length=64)),
                ('source_asset', models.ForeignKey(db_column='source_asset_id', on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='discovery.asset')),
                ('target_asset', models.ForeignKey(db_column='target_asset_id', on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='discovery.asset')),
            ],
            options={
                'db_table': 'asset_relationships',
            },
        ),
        migrations.CreateModel(
            name='AssetTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=255)),
                ('value', models.CharField(blank=True, max_length=512)),
                ('asset', models.ForeignKey(db_column='asset_id', on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='discovery.asset')),
            ],
            options={
                'db_table': 'asset_tags',
            },
        ),
        migrations.CreateModel(
            name='AssetVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(db_column='asset_id', on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='discovery.asset')),
            ],
            options={
                'db_table': 'asset_versions',
            },
        ),
    ]
