"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import {
  MessageCircle,
  CheckCircle,
  Clock,
  Shield,
  BarChart3,
  FileText,
  Cpu,
  BookOpen,
  Heart,
  Search,
  Users,
  Calendar,
  Phone,
  Mail,
} from "lucide-react";
import Link from "next/link";
import { useToast } from "@/hooks/use-toast";
import { PageHero } from "@/components/page-hero";
import { PageLayout } from "@/components/page-layout";

const API_BASE = process.env.NEXT_PUBLIC_API_BASE_URL ?? (typeof window !== "undefined" ? "" : "http://localhost:8000");

const SERVICES = [
  {
    id: "compliance-readiness",
    title: "Compliance Readiness Assessment",
    description:
      "A structured evaluation of your current security and compliance posture to determine readiness for frameworks such as SOC 2, ISO 27001, and other governance standards.",
    includes: [
      "Review of infrastructure and security posture",
      "Identification of compliance gaps",
      "Control mapping against required frameworks",
      "Risk and readiness assessment",
      "Prioritized compliance roadmap",
    ],
    closing: "This engagement helps organizations understand where they stand and what steps are required to reach audit readiness.",
    icon: Shield,
  },
  {
    id: "infrastructure-risk",
    title: "Infrastructure & Risk Analysis",
    description:
      "Deep analysis of infrastructure configurations, system health, and operational risk signals generated by the Opticini platform.",
    includes: [
      "Infrastructure insight interpretation",
      "Configuration risk analysis",
      "Operational bottleneck identification",
      "System architecture review",
      "Prioritized risk mitigation recommendations",
    ],
    closing: "Our goal is to help teams convert platform insights into meaningful operational improvements.",
    icon: BarChart3,
  },
  {
    id: "compliance-implementation",
    title: "Compliance Implementation Strategy",
    description:
      "Guidance on implementing compliance frameworks efficiently while minimizing operational disruption.",
    includes: [
      "Framework implementation planning",
      "Policy and control mapping",
      "Evidence collection strategy",
      "Integration planning with existing systems",
      "Implementation timeline and milestones",
    ],
    closing: "This service ensures organizations can move from planning to execution with confidence.",
    icon: FileText,
  },
  {
    id: "technical-advisory",
    title: "Technical Advisory",
    description:
      "Expert guidance on infrastructure architecture, system integrations, and governance automation using Opticini.",
    includes: [
      "Architecture review and recommendations",
      "Infrastructure design consultation",
      "Integration planning",
      "Tool selection guidance",
      "Compliance automation strategies",
    ],
    closing: "Technical advisory helps organizations build a sustainable and scalable compliance infrastructure.",
    icon: Cpu,
  },
  {
    id: "team-training",
    title: "Team Training & Workshops",
    description:
      "Hands-on training programs that teach teams how to operate compliance and infrastructure monitoring programs effectively.",
    includes: [
      "Opticini platform training",
      "Compliance operations workshops",
      "Audit preparation training",
      "Infrastructure monitoring best practices",
      "Team enablement sessions",
    ],
    closing: "Training empowers teams to maintain compliance and operational excellence independently.",
    icon: BookOpen,
  },
  {
    id: "ongoing-advisory",
    title: "Ongoing Advisory & Support",
    description:
      "Continuous expert guidance to help organizations maintain compliance readiness and operational visibility.",
    includes: [
      "Regular compliance check-ins",
      "Infrastructure monitoring guidance",
      "Support with audit preparation",
      "Progress tracking and reporting",
      "Advisory support for emerging risks",
    ],
    closing: "This service ensures organizations maintain momentum as their infrastructure and compliance requirements evolve.",
    icon: Heart,
  },
  {
    id: "full-audit",
    title: "Full Compliance & Infrastructure Audit",
    description:
      "A comprehensive engagement that combines readiness assessment, infrastructure analysis, and optimization planning.",
    includes: [
      "Complete compliance readiness review",
      "Infrastructure and risk assessment",
      "Multi-framework analysis",
      "Comprehensive improvement roadmap",
      "Prioritized action plan",
    ],
    closing: "This engagement provides organizations with a clear path toward long-term compliance and infrastructure resilience.",
    icon: Search,
  },
];

export default function ConsultPage() {
  const [formData, setFormData] = useState({
    name: "",
    email: "",
    company: "",
    phone: "",
    service: "",
    message: "",
  });
  const [isSubmitting, setIsSubmitting] = useState(false);
  const { toast } = useToast();

  const handleInputChange = (field: string, value: string) => {
    setFormData((prev) => ({ ...prev, [field]: value }));
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsSubmitting(true);

    try {
      const response = await fetch(`${API_BASE}/api/consultation/`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(formData),
      });

      const result = await response.json();

      if (response.ok && result.success) {
        toast({
          title: "Consultation Request Submitted",
          description: "We'll get back to you within 24 hours with next steps.",
        });
        setFormData({ name: "", email: "", company: "", phone: "", service: "", message: "" });
      } else {
        throw new Error(result.error || "Failed to submit consultation request");
      }
    } catch {
      toast({
        title: "Error",
        description: "Failed to submit consultation request. Please try again.",
        variant: "destructive",
      });
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <PageLayout>
      <PageHero
        badge="Talk to Sales"
        title="Expert Compliance & Infrastructure Consulting"
        subtitle="Turn compliance complexity into operational clarity."
      />

      {/* Intro */}
      <section className="pt-16 mt-12 py-12 px-4 border-b" style={{ background: "var(--rd-bg-white)", borderColor: "var(--rd-border-light)" }}>
        <div className="max-w-3xl mx-auto text-center">
          <p className="text-lg leading-relaxed mb-4" style={{ color: "var(--rd-text-secondary)" }}>
            Opticini offers professional consulting services designed to help organizations understand their infrastructure posture, prepare for audits, and implement strong compliance and governance practices.
          </p>
          <p className="text-base leading-relaxed" style={{ color: "var(--rd-text-secondary)" }}>
            Our experts work alongside your teams to interpret system insights, identify risks, and create practical improvement strategies that move your organization toward continuous compliance.
          </p>
        </div>
      </section>

      {/* Our Consulting Services */}
      <section className="py-16 px-4" style={{ background: "var(--rd-bg-subtle)" }}>
        <div className="container mx-auto max-w-7xl">
          <div className="text-center mb-16">
            <h2 className="text-3xl md:text-4xl font-bold mb-4" style={{ color: "var(--rd-text-heading)", fontFamily: "var(--font-sora), sans-serif" }}>
              Our Consulting Services
            </h2>
            <p className="text-xl max-w-3xl mx-auto" style={{ color: "var(--rd-text-secondary)" }}>
              Comprehensive advisory services designed to support your organization's compliance and infrastructure maturity.
            </p>
          </div>

          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
            {SERVICES.map((service) => {
              const Icon = service.icon;
              return (
                <div
                  key={service.id}
                  className="bg-white border-[1.5px] rounded-[18px] p-8 transition-all hover:border-[#93c5fd] hover:shadow-lg"
                  style={{ borderColor: "var(--rd-border-light)" }}
                >
                  <div
                    className="w-14 h-14 rounded-xl flex items-center justify-center mb-5"
                    style={{ background: "var(--rd-blue-50)" }}
                  >
                    <Icon className="h-7 w-7" style={{ color: "var(--rd-blue-600)" }} />
                  </div>
                  <h3 className="text-xl font-bold mb-3" style={{ color: "var(--rd-text-heading)", fontFamily: "var(--font-sora), sans-serif" }}>
                    {service.title}
                  </h3>
                  <p className="text-sm mb-5 leading-relaxed" style={{ color: "var(--rd-text-secondary)" }}>
                    {service.description}
                  </p>
                  <p className="text-xs font-bold uppercase tracking-wider mb-3" style={{ color: "var(--rd-blue-600)" }}>
                    Includes
                  </p>
                  <ul className="space-y-2 mb-5">
                    {service.includes.map((item, i) => (
                      <li key={i} className="flex items-start gap-2 text-sm" style={{ color: "var(--rd-text-secondary)" }}>
                        <CheckCircle className="h-4 w-4 mt-0.5 shrink-0" style={{ color: "var(--rd-blue-600)" }} />
                        {item}
                      </li>
                    ))}
                  </ul>
                  <p className="text-sm leading-relaxed" style={{ color: "var(--rd-text-secondary)" }}>
                    {service.closing}
                  </p>
                </div>
              );
            })}
          </div>
        </div>
      </section>

      {/* Consultant & Auditor Partnerships */}
      <section className="py-16 px-4" style={{ background: "var(--rd-bg-white)" }}>
        <div className="container mx-auto max-w-4xl">
          <h2 className="text-2xl md:text-3xl font-bold mb-6 text-center" style={{ color: "var(--rd-text-heading)", fontFamily: "var(--font-sora), sans-serif" }}>
            Consultant & Auditor Partnerships
          </h2>
          <p className="text-lg mb-8 text-center leading-relaxed" style={{ color: "var(--rd-text-secondary)" }}>
            Opticini also supports independent consultants and audit professionals through our partner program. Consultants can onboard and manage multiple client organizations within the platform while providing advisory services and preparing clients for formal audits.
          </p>
          <p className="text-sm font-bold uppercase tracking-wider mb-4 text-center" style={{ color: "var(--rd-blue-600)" }}>
            Partners benefit from
          </p>
          <div className="flex flex-wrap justify-center gap-4">
            {["Multi-client management tools", "Audit readiness workflows", "Referral and affiliate revenue opportunities", "Collaboration tools for client engagements"].map((item) => (
              <div
                key={item}
                className="px-5 py-3 rounded-xl border-[1.5px]"
                style={{ borderColor: "var(--rd-border-light)", background: "var(--rd-bg-subtle)", color: "var(--rd-text-heading)" }}
              >
                {item}
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Request a Consultation */}
      <section id="schedule" className="py-16 px-4 scroll-mt-24" style={{ background: "var(--rd-bg-subtle)" }}>
        <div className="container mx-auto max-w-4xl">
          <div className="text-center mb-12">
            <h2 className="text-3xl md:text-4xl font-bold mb-4" style={{ color: "var(--rd-text-heading)", fontFamily: "var(--font-sora), sans-serif" }}>
              Request a Consultation
            </h2>
            <p className="text-xl" style={{ color: "var(--rd-text-secondary)" }}>
              Tell us about your compliance or infrastructure challenges, and our experts will help you develop a clear path toward stronger governance, operational insight, and audit readiness.
            </p>
          </div>

          <div className="grid lg:grid-cols-2 gap-8">
            <div
              className="bg-white border-[1.5px] rounded-[18px] p-8"
              style={{ borderColor: "var(--rd-border-light)" }}
            >
              <form onSubmit={handleSubmit} className="space-y-6">
                <div className="grid md:grid-cols-2 gap-6">
                  <div>
                    <Label htmlFor="name">Full Name *</Label>
                    <Input
                      id="name"
                      value={formData.name}
                      onChange={(e) => handleInputChange("name", e.target.value)}
                      required
                      className="mt-1 rounded-lg border-[1.5px]"
                      style={{ borderColor: "var(--rd-border-light)" }}
                    />
                  </div>
                  <div>
                    <Label htmlFor="email">Email *</Label>
                    <Input
                      id="email"
                      type="email"
                      value={formData.email}
                      onChange={(e) => handleInputChange("email", e.target.value)}
                      required
                      className="mt-1 rounded-lg border-[1.5px]"
                      style={{ borderColor: "var(--rd-border-light)" }}
                    />
                  </div>
                </div>
                <div className="grid md:grid-cols-2 gap-6">
                  <div>
                    <Label htmlFor="company">Company</Label>
                    <Input
                      id="company"
                      value={formData.company}
                      onChange={(e) => handleInputChange("company", e.target.value)}
                      className="mt-1 rounded-lg border-[1.5px]"
                      style={{ borderColor: "var(--rd-border-light)" }}
                    />
                  </div>
                  <div>
                    <Label htmlFor="phone">Phone</Label>
                    <Input
                      id="phone"
                      value={formData.phone}
                      onChange={(e) => handleInputChange("phone", e.target.value)}
                      className="mt-1 rounded-lg border-[1.5px]"
                      style={{ borderColor: "var(--rd-border-light)" }}
                    />
                  </div>
                </div>
                <div>
                  <Label htmlFor="service">Service of Interest *</Label>
                  <Select value={formData.service} onValueChange={(v) => handleInputChange("service", v)}>
                    <SelectTrigger className="mt-1 rounded-lg border-[1.5px]" style={{ borderColor: "var(--rd-border-light)" }}>
                      <SelectValue placeholder="Select a service" />
                    </SelectTrigger>
                    <SelectContent>
                      {SERVICES.map((s) => (
                        <SelectItem key={s.id} value={s.id}>
                          {s.title}
                        </SelectItem>
                      ))}
                      <SelectItem value="custom">Custom / Other</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
                <div>
                  <Label htmlFor="message">Tell us about your challenges *</Label>
                  <Textarea
                    id="message"
                    value={formData.message}
                    onChange={(e) => handleInputChange("message", e.target.value)}
                    required
                    rows={4}
                    placeholder="Describe your compliance or infrastructure challenges and what you hope to achieve..."
                    className="mt-1 rounded-lg border-[1.5px] resize-none"
                    style={{ borderColor: "var(--rd-border-light)" }}
                  />
                </div>
                <Button
                  type="submit"
                  disabled={isSubmitting}
                  className="w-full rounded-lg font-semibold py-6"
                  style={{ background: "var(--rd-blue-600)", color: "#fff" }}
                >
                  {isSubmitting ? (
                    <>
                      <Clock className="h-5 w-5 mr-2 animate-spin" />
                      Submitting...
                    </>
                  ) : (
                    <>
                      <MessageCircle className="h-5 w-5 mr-2" />
                      Schedule a Consultation
                    </>
                  )}
                </Button>
              </form>
            </div>

            <div
              className="bg-white border-[1.5px] rounded-[18px] p-8 lg:sticky lg:top-24"
              style={{ borderColor: "var(--rd-border-light)" }}
            >
              <div className="flex items-center gap-3 mb-6">
                <div className="w-12 h-12 rounded-xl flex items-center justify-center" style={{ background: "var(--rd-blue-50)" }}>
                  <Calendar className="h-6 w-6" style={{ color: "var(--rd-blue-600)" }} />
                </div>
                <div>
                  <h3 className="font-bold" style={{ color: "var(--rd-text-heading)", fontFamily: "var(--font-sora), sans-serif" }}>
                    Schedule Your Call
                  </h3>
                  <p className="text-sm" style={{ color: "var(--rd-text-secondary)" }}>
                    We respond within 24 hours
                  </p>
                </div>
              </div>
              <p className="text-sm mb-6 leading-relaxed" style={{ color: "var(--rd-text-secondary)" }}>
                Choose a time that works best for you. We'll send you a calendar invite with meeting details.
              </p>
              <div className="space-y-3 mb-6">
                <div className="flex justify-between p-3 rounded-lg text-sm" style={{ background: "var(--rd-bg-subtle)" }}>
                  <span style={{ color: "var(--rd-text-secondary)" }}>Monday – Friday</span>
                  <span className="font-medium" style={{ color: "var(--rd-blue-600)" }}>9 AM – 6 PM</span>
                </div>
                <div className="flex justify-between p-3 rounded-lg text-sm" style={{ background: "var(--rd-bg-subtle)" }}>
                  <span style={{ color: "var(--rd-text-secondary)" }}>Saturday</span>
                  <span className="font-medium" style={{ color: "var(--rd-blue-600)" }}>10 AM – 4 PM</span>
                </div>
              </div>
              <div className="pt-6 border-t" style={{ borderColor: "var(--rd-border-light)" }}>
                <h4 className="font-semibold mb-3" style={{ color: "var(--rd-text-heading)", fontFamily: "var(--font-sora), sans-serif" }}>
                  Quick Contact
                </h4>
                <div className="space-y-2 text-sm" style={{ color: "var(--rd-text-secondary)" }}>
                  <div className="flex items-center gap-2">
                    <Phone className="h-4 w-4" />
                    <span>(555) 123-4567</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <Mail className="h-4 w-4" />
                    <span>consult@opticini.com</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="py-16 px-4 text-white" style={{ background: "linear-gradient(160deg, var(--rd-blue-700), var(--rd-blue-600), var(--rd-blue-500))" }}>
        <div className="container mx-auto max-w-4xl text-center">
          <h2 className="text-2xl md:text-3xl font-bold mb-4" style={{ fontFamily: "var(--font-sora), sans-serif" }}>
            Transform your compliance operations
          </h2>
          <p className="text-lg text-white/90 mb-8">
            Schedule a consultation to begin transforming your compliance operations with Opticini.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Button asChild size="lg" className="bg-white rounded-lg font-semibold hover:bg-white/95" style={{ color: "var(--rd-blue-700)" }}>
              <Link href="/request-demo">
                <MessageCircle className="h-5 w-5 mr-2" />
                Request Demo
              </Link>
            </Button>
            <Button asChild size="lg" variant="outline" className="border-2 border-white/50 text-white hover:bg-white/10 rounded-lg">
              <Link href="/#platform">
                <Users className="h-5 w-5 mr-2" />
                See Platform
              </Link>
            </Button>
          </div>
        </div>
      </section>
    </PageLayout>
  );
}
