# Generated by Django 5.2.6 on 2026-03-01 04:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_seed_countries_multi_region'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VersionRelease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=50, unique=True)),
                ('release_notes', models.TextField(blank=True, help_text='Changes in this release')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending approval'), ('approved', 'Approved')], default='draft', max_length=20)),
                ('is_current', models.BooleanField(default=False, help_text='If True, this version is served by /api/version/')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, db_column='approved_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_version_releases', to=settings.AUTH_USER_MODEL)),
                ('proposed_by', models.ForeignKey(blank=True, db_column='proposed_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_version_releases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Version release',
                'verbose_name_plural': 'Version releases',
                'db_table': 'version_releases',
                'ordering': ['-created_at'],
            },
        ),
    ]
