# Generated by Django 5.2.6 on 2026-03-10 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_user_tables_back_to_core'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationregion',
            name='country',
        ),
        migrations.RemoveField(
            model_name='environment',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='team',
            name='organization',
        ),
        migrations.AlterUniqueTogether(
            name='organizationregion',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='orgconnectormodulescope',
            name='org_connector',
        ),
        migrations.AlterUniqueTogether(
            name='orgconnectormodulescope',
            unique_together=None,
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='OrganizationRegion',
        ),
        migrations.DeleteModel(
            name='Environment',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='OrgConnector',
        ),
        migrations.DeleteModel(
            name='OrgConnectorModuleScope',
        ),
    ]
