# Generated by Django 5.2.6 on 2026-03-10 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_user_tables_back_to_core'),
    ]

    operations = [
        # Drop unique_together before RemoveField (0016 used country_id in unique_together;
        # Django expects field names - drop via RunSQL to avoid KeyError)
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'core' AND table_name = 'organization_regions') THEN
                    ALTER TABLE core.organization_regions DROP CONSTRAINT IF EXISTS organization_regions_organization_id_country_id_key;
                END IF;
            END $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='organizationregion',
                    unique_together=None,
                ),
            ],
        ),
        migrations.RemoveField(
            model_name='organizationregion',
            name='country',
        ),
        migrations.RemoveField(
            model_name='environment',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='team',
            name='organization',
        ),
        # Drop unique_together before RemoveField (field must exist for AlterUniqueTogether)
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'core' AND table_name = 'org_connector_module_scope') THEN
                    ALTER TABLE core.org_connector_module_scope DROP CONSTRAINT IF EXISTS org_connector_module_scope_org_connector_id_module_key;
                END IF;
            END $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='orgconnectormodulescope',
                    unique_together=None,
                ),
            ],
        ),
        migrations.RemoveField(
            model_name='orgconnectormodulescope',
            name='org_connector',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='OrganizationRegion',
        ),
        migrations.DeleteModel(
            name='Environment',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='OrgConnector',
        ),
        migrations.DeleteModel(
            name='OrgConnectorModuleScope',
        ),
    ]
