# Generated by Django 5.2.6 on 2026-03-10 22:08
# Fixed: core.0019 already drops these tables. Use state-only update to avoid
# "relation does not exist" when running on fresh DB or after 0019.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_user_tables_back_to_core'),
    ]

    operations = [
        # Tables were dropped by core.0019. Only update migration state.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='organizationregion',
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name='organizationregion',
                    name='country',
                ),
                migrations.RemoveField(
                    model_name='environment',
                    name='organization',
                ),
                migrations.RemoveField(
                    model_name='team',
                    name='organization',
                ),
                migrations.AlterUniqueTogether(
                    name='orgconnectormodulescope',
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name='orgconnectormodulescope',
                    name='org_connector',
                ),
                migrations.DeleteModel(
                    name='Country',
                ),
                migrations.DeleteModel(
                    name='OrganizationRegion',
                ),
                migrations.DeleteModel(
                    name='Environment',
                ),
                migrations.DeleteModel(
                    name='Organization',
                ),
                migrations.DeleteModel(
                    name='Team',
                ),
                migrations.DeleteModel(
                    name='OrgConnector',
                ),
                migrations.DeleteModel(
                    name='OrgConnectorModuleScope',
                ),
            ],
            database_operations=[],  # No-op: tables already dropped by 0019
        ),
    ]
